### ISSUE TITLE
Using dashboard is randomly switching between cluster nodes? How to get cluster wide info?

### ISSUE THREAD

**Issue by jasperslot** [RedisGrafana/grafana-redis-datasource#134]
## Summary
I have a Redis cluster running within k8s. This cluster consists of 3 masters & 3 slaves. Within this same k8s cluster I have a Grafana deployment. From within this Grafana instance I have configured a redis data source. It's configured as type cluster, with an address pointing to a k8s cluster ip service. Pool size 0, timeout 10s. As a dashboard I use the default dashboard provided by this plugin. 

The connection is working, but for some reason the Main & Other section are constantly (every 5? seconds) changing to a different node. Why? I want to able to see the number all keys of the whole cluster for example. Now it's impossible to do so? I also want to have info of a certain key with the LLEN command. The pitty is, it only shows the number when I am at the right node. So I have to wait through the cycle.

Maybe I simply overlook something, I am pretty new to both Grafana and Redis.

## Relevant information
Grafana v7.3.6
grafana-redis-datasource v1.3.0
Redis v6.0.9

**Comment by mikhailredis** [comment]
@jasperslot Thank you for the great question. I would recommend looking at https://redis.io/topics/cluster-tutorial to learn more about OSS Redis Cluster. When you connect to the Redis Cluster and execute commands like `INFO`, they will be executed on any available node. A predefined Redis dashboard will give you mixed information from all available nodes as you can see. To see aggregated information I would recommend creating custom dashboards, use Redis Proxy or Redis Enterprise.

Using cluster mode makes sense when you are working with Redis data. `LLEN` command should be executed successfully every time. Redis Cluster should move the request to the current node according to hash slots. We have to investigate why you see the result only on the specific node. I just tried it and it works as expected.

To properly monitor each master shard, you will need to create a separate data source for each. There is a Redis App (https://github.com/RedisGrafana/grafana-redis-app) which makes it a little bit easier to manage them and has a dashboard to support multiple data sources.

Could you please send me screenshots of the data source configuration and panel for the `LLEN` command to check?

**Comment by jasperslot** [comment]
@mikhailredis Thanks for your comprehensive answer. I will look into Redis Proxy (although this one is still in beta?) & Redis App to see which suits my needs best. It seems that LLEN is working correctly indeed. Since the value was changing a lot, I thought it might happen because of the switching of nodes. Sorry, my mistake.

**Comment by mikhailredis** [comment]
@jasperslot Thank you for confirming regarding the `LLEN` command. You can also try Streaming mode to see the changes in the graph.

Another option to Redis Proxy will be Redis Enterprise, which you can install on the K8S cluster or Redis Enterprise Cloud. Please let me know if you have any questions.
