### ISSUE TITLE
Time series does not work when streaming is turned on

### ISSUE THREAD

**Issue by miohtama** [RedisGrafana/grafana-redis-datasource#147]
## Summary

Does time series (TS.RANGE, TS.MRANGE) support streaming?

## Relevant information

Here is the same TS.RANGE explorer with and without streaming. It does not seem to do anything when streaming is turned on.

No streaming:

<img width="1593" alt="image" src="https://user-images.githubusercontent.com/49922/105423400-b5f28200-5c45-11eb-9d05-a54158ab93b2.png">

Streaming:

<img width="1579" alt="image" src="https://user-images.githubusercontent.com/49922/105423335-9fe4c180-5c45-11eb-9c75-246feabd307b.png">

Instead of value there is "Field 2" in the tabular data.

**Comment by mikhailredis** [comment]
@miohtama Thank you for opening the issue. Streaming currently does not support multi-line responses like TS.RANGE and TS.MRANGE. You can use TS.GET command in streaming mode which returns the latest value.

We will add Streaming to TS.RANGE and TS.MRANGE command shortly.

**Comment by miohtama** [comment]
Thank you so much @mikhailredis. Pardon my lack of earlier experience with Grafana, but what would you recommend as an alternative to emulate TS.MRANGE like graphs (multiple lines) for streaming? I assume this can be done with templates and somehow automatically generated from redis keys? If there are any existing examples for Redis Datasource, happy to take a look.

**Comment by mikhailredis** [comment]
@miohtama Could you please provide more details on why do you need streaming for your graphs? What advantages do you see compare to static dashboards, which refresh every 30 seconds or so?

**Comment by miohtama** [comment]
@mikhailredis You are correct, there are no substantive advantages, except able to toggle the Streaming button on the Grafana UI. I am not experienced enough to tell if Grafana has some special treatment for Streaming dashboards.

**Comment by mikhailredis** [comment]
@miohtama There is a limited number of data sources that support Streaming in Grafana and Redis is one of them. We introduced streaming to display Redis statistics on the graph.

I will take a look and see if I can tweak Streaming in the data source to support multi-lines for Time-Series.

**Comment by miohtama** [comment]
I will close this issue. Thank you for the good support. 

Meanwhile I assume there is no way to disable Streaming button in the Grafana UI if the source does not support streaming? I might open an issue with Grafana if this is a common UX issue with other data sources as well.

**Comment by mikhailredis** [comment]
@miohtama I am sorry for the delay. We updated the Streaming option in the Redis Data Source and it will be a part of the upcoming release. The streaming button is a part of Redis Data Source and now it's fully implemented using time series or data frames.
