### ISSUE TITLE
What are the supported Label Filter operations?

### ISSUE THREAD

**Issue by miohtama** [RedisGrafana/grafana-redis-datasource#153]
## Summary

This might not be Redis data source specific questions, but a generic Grafana question, so please bear with me if I am asking in the wrong place.

What kind of operations are supported for label filter and where are these documented? E.g. how to do 'AND', 'OR' and such.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/49922/106275884-e2566180-6236-11eb-86c4-e62b020522f7.png">

The tooltip only says "Label filter"

**Comment by mikhailredis** [comment]
@miohtama It's related to RedisTimeSeries filtering rules: https://oss.redislabs.com/redistimeseries/commands/#filtering

Please take a look and let me know if you have any questions.

**Comment by mikhailredis** [comment]
@miohtama Thank you for the feedback. The filter's tooltip was updated with the link to RedisTimeSeries filtering.
