### ISSUE TITLE
Getting the last value of multiple RedisTimeSeries keys to a table?

### ISSUE THREAD

**Issue by miohtama** [RedisGrafana/grafana-redis-datasource#154]
## Summary

I am creating a table panel that displays the latest value of multiple Redis TimeSeries keys. Keys are filtered by a label query. For a stock market example, the resulting table would look like:

```
| key     | value |
| AAPL    | 100.0 |
| TSLA    | 123.2 |
```

... where in the Redis I have created multiple time series keys where each key has label="stockmarket".

A Python key set up code would look like:

```python
rts.create("aapl", labels={"type": "stockmarket"})
rts.create("tesla", labels={"type": "stockmarket"})
```
I can create a graph for the same kind of data simply with `TS.MRANGE` query.

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/49922/106296055-78978100-6251-11eb-9fd7-5d64f6331395.png">

However, I am not sure what is the correct way to transfer `TS.MRANGE` result to key -> latest value table. I would appreciate any pointers, as I tried with Transforms and also with writing a pure Redis CLI query, but not figure out how ot make it output latest values in a nice key->value table.

**Comment by mikhailredis** [comment]
@miohtama Thank you for your interest in RedisTimeSeries.

This is how you add the time series using `redis-cli`:
```
127.0.0.1:6379> ts.add tesla * 500 labels type stockmarket id tesla
(integer) 1611989402765
127.0.0.1:6379> ts.add aapl * 250 labels type stockmarket id aapl
(integer) 1611989410546
127.0.0.1:6379> ts.add aapl * 210 labels type stockmarket id aapl
(integer) 1611989417419
127.0.0.1:6379> ts.add tesla * 300 labels type stockmarket id tesla
(integer) 1611989423210
127.0.0.1:6379> ts.add tesla * 350 labels type stockmarket id tesla
(integer) 1611989429495
```

To query using filter using `redis-cli`:
````
127.0.0.1:6379> ts.mrange - + WITHLABELS filter type=stockmarket
1) 1) "aapl"
   2) 1) 1) "type"
         2) "stockmarket"
      2) 1) "id"
         2) "aapl"
   3) 1) 1) (integer) 1611989384722
         2) 200
      2) 1) (integer) 1611989410546
         2) 250
      3) 1) (integer) 1611989417419
         2) 210
2) 1) "tesla"
   2) 1) 1) "type"
         2) "stockmarket"
      2) 1) "id"
         2) "tesla"
   3) 1) 1) (integer) 1611989402765
         2) 500
      2) 1) (integer) 1611989423210
         2) 300
      3) 1) (integer) 1611989429495
         2) 350
127.0.0.1:6379> 
```

In Grafana I would do it as Stats or Graph:
  1) Add Stat panel with RedisTimeSeries -> TS.MRANGE
  2) Set Label Filter as `type=stockmarket` and Legend Label as `type` and Value Label as `id`
  3) In Transformations add Merge
  4) Choose Display -> Calculation as `Last (not null)`

![Screen Shot 2021-01-29 at 10 57 36 PM](https://user-images.githubusercontent.com/47795110/106349823-eb225400-6285-11eb-9434-9de497082801.png)

![Screen Shot 2021-01-29 at 10 53 04 PM](https://user-images.githubusercontent.com/47795110/106349825-f2e1f880-6285-11eb-8f5a-e80872b872ca.png)

Please let me know if it works for you.

**Comment by miohtama** [comment]
Thank yu Mikhail. I think `Calculation` was the part I was missing and will try it out today.

**Comment by mikhailredis** [comment]
@miohtama, Let me know if there is anything else.

**Comment by mikhailredis** [comment]
@miohtama Please share your results, I would love to see them.
