### ISSUE TITLE
Alerting for Grafana-Redis-Datasource

### ISSUE THREAD

**Issue by sunilgithu-public** [RedisGrafana/grafana-redis-datasource#166]
Hi Folks,

Recently I have set up Grafana-Redis-Datasource. It works fine with the amazing graphs and real time monitoring data.
I am looking to have alerts for these monitored data. Say like if the memory goes beyond 85%, CPU usage go beyond 95% etc.
I am not able to see any alerting configuration options. If there is any way to get the alerts for what is being monitored it would be great. I am new to the MaaS and the Grafana-Redis-Datasource. Please help me here to config alerts. 

Thanks,
Sunil

**Comment by sunilgithu-public** [comment]
folks, 
If any alerting related info/method is available and can be shared with me , would be highly appreciated.

**Comment by sunilgithu-public** [comment]
@mikhailredis : If any alerting related info/method is available and can be shared with me , would be highly appreciated.

**Comment by mikhailredis** [comment]
@sunilgithu-public i am sorry for the delay, I planned to look into it today. Are you looking to alert on specific data or info commands?

**Comment by sunilgithu-public** [comment]
@mikhailredis Thank you for the response. I am glad you are going to look into it :)
Alerts for memory and CPU , i had mentioned in my question as an example. 
Basically, I am looking to have alerts for all of the data that the plugin is monitoring...  from both the Dashboards "Redis" and "Redis Streaming" when a certain threshold exceeds.

1.Take example like If the uptime was 3 weeks until mrng and now its 1 min on dashboard. which means like DB stopped and started due to some reason so for this need an alert. But on dashboard i see only 2 option for uptime i.e. Query and Transform. There is no option for alert.
2.Take example like no. of connected clients suddenly goes from 50 to 500 so if the threshold can be set to 100 and if it breaches then we get an alert. But here also only 2 option and no option for Alert.
3. For Memory and CPU i tried to set up alert but i get something like "Transformations are not supported in alert queries".
4. If i try to take away transformation option and try to set up alert then graph becomes blank.

**Comment by sunilgithu-public** [comment]
@mikhailredis Request your help on my above queries.

**Comment by mikhailredis** [comment]
@sunilgithu-public "If transformations are configured, alerts will not behave as expected so we should not let them be configured" and were disabled in 6.4.0-beta1(https://github.com/grafana/grafana/pull/19027).

I am looking into it.

**Comment by mikhailredis** [comment]
@sunilgithu-public I was able to use Alerts with TS.GET command so far. Alerts are working only for time-series data (data frames with the `time` field) because processed on the backend.

In current implementation:
- Streaming adds a `time` field on the frontend
- Redis Data Source does not support filtering in the data source as Transformations was designed to do that. Alerts do not support filters either.

I have an idea to move a `time` field from the frontend on the backend to support alerting and also add labels with filtering to all fields. I will experiment tomorrow and let you know.

**Comment by sunilgithu-public** [comment]
@mikhailredis thank you :) much appreciated. Awaiting your positive response.

**Comment by mikhailredis** [comment]
@sunilgithu-public I will let you know. Also, I found FR for Grafana: https://github.com/grafana/grafana/issues/26516

**Comment by sunilgithu-public** [comment]
@mikhailredis hoping you would have come up with something for the alerts :)

**Comment by mikhailredis** [comment]
> @mikhailredis hoping you would have come up with something for the alerts :)

I did. Will share later today.

**Comment by sunilgithu-public** [comment]
@mikhailredis thank you. eagerly waiting to hear from you!

**Comment by sunilgithu-public** [comment]
@mikhailredis requesting your response on this.

**Comment by mikhailredis** [comment]
@sunilgithu-public I am sorry for the delay, but this feature is more complicated than I expected and requires introducing Alerting for each command separately, there is no unified way to add it to all commands similar to streaming.

I am still working on it and will get back to you shortly.

**Comment by sunilgithu-public** [comment]
@mikhailredis thank you. much appreciated. I will bookmark this thread for future updates.

**Comment by sunilgithu-public** [comment]
@mikhailredis requesting your response on this.

**Comment by mikhailredis** [comment]
@sunilgithu-public Almost done with Documentation. I will work on Alerting next.

**Comment by sunilgithu-public** [comment]
@mikhailredis Requesting your response on this.

**Comment by mikhailredis** [comment]
@sunilgithu-public I am sorry for the multiple delays. I decided not to introduced Alerting and Streaming updates in the 1.4.0 release to avoid adding any breaking changes.

![Screen Shot 2021-05-12 at 10 26 05 PM](https://user-images.githubusercontent.com/47795110/118069576-6bbb1b00-b372-11eb-982c-670c90b3bfad.png)

PR is submitted. I will add more tests tomorrow and merge to the main branch tomorrow.

**Comment by sunilgithu-public** [comment]
@mikhailredis thank you for the updates :)

**Comment by mikhailredis** [comment]
@sunilgithu-public PR merged and `redis-app` should be rebuild in 5 minutes: https://github.com/orgs/RedisGrafana/packages/container/package/redis-app

Please verify and let me know if you have any questions.
Documentation will be updated in https://github.com/RedisGrafana/RedisGrafana/issues/31

**Comment by AlexeiZenin** [comment]
Can't seem to create a standalone alert for memory in 9.1.0 Grafana and get this error message: `Failed to evaluate queries and expressions: failed to execute conditions: input data must be a wide series but got type not (input refid)`

<img width="1233" alt="Screen Shot 2022-09-01 at 12 18 37 PM" src="https://user-images.githubusercontent.com/12644364/187963534-598f97b2-2651-4e0f-8021-31c6ac63f009.png">

**Comment by mikhail-vl** [comment]
@AlexeiZenin Please open a separate issue for Redis team to investigate.

**Comment by AlexeiZenin** [comment]
Which repository would that be and what would the Redis team do to fix this? From my understanding this plugin reads data from Redis, the dashboards all work great, just seems the alerting integration doesn't work for this.

**Comment by AlexeiZenin** [comment]
Ah I see, I will open a new issue here then, thanks!

**Comment by peter-nguyen-rw** [comment]
@mikhail-vl 
So is this still not something available to the Redis plugin?
