### ISSUE TITLE
Allow multiple Streaming queries per panel

### ISSUE THREAD

**Issue by phumberdroz** [RedisGrafana/grafana-redis-datasource#169]
### Describe the solution you'd like
I would like to able to have more than one stream in a panel. This is useful for me as I want to display a table with rows that are all from different keys.
### Describe alternatives you've considered

I could not come up with alternatives. Especially since the redis data source seems to be the only publicly available data source that supports streaming. 

### Additional context

With #57 streaming was introduced.

**Comment by mikhailredis** [comment]
@phumberdroz Have you tried to use different queries and then combine them using Transformations?

**Comment by mikhailredis** [comment]
@phumberdroz Are you talking about Streaming data or Redis Streams? Could you please provide more details.

**Comment by phumberdroz** [comment]
I am talking about streaming multiple Grafana Queries at the same time from Redis.

This is what the hint currently says:
> If checked, the datasource will stream data. **Only Ref A is supported.**

**Comment by mikhailredis** [comment]
@phumberdroz Thank you, I updated the title to `Streaming Queries` to avoid confusion with Redis Streams.
I will work on it and get back to you shortly.

**Comment by phumberdroz** [comment]
Thank you so much for adding this 🎉

**Comment by mikhailredis** [comment]
@phumberdroz Thank you and I am sorry for the delay.
You can test it using the nightly Docker image and let me know if it works for you.
