### ISSUE TITLE
XRANGE support for streaming

### ISSUE THREAD

**Issue by bauagonzo** [RedisGrafana/grafana-redis-datasource#172]
### Is your enhancement related to a problem? Please describe.
It would be nice that XRANGE request support streaming for real-time update

### Describe the solution you'd like
XRANGE support a request for a timeframe between two timestamps. It will be nice to use it to stream realtime data points to Grafana charts

**Comment by mikhailredis** [comment]
@bauagonzo Thank you for your questions. It's actually supported if you enable Streaming as Data Frames:

![Screen Shot 2021-03-11 at 8 55 17 AM](https://user-images.githubusercontent.com/47795110/110797864-97713600-8247-11eb-842e-b4046ff4c29a.png)

Is it what you are looking for or something else?

**Comment by mikhailredis** [comment]
It works as a chart as well using Streaming as Time Series:

![Screen Shot 2021-03-11 at 8 59 23 AM](https://user-images.githubusercontent.com/47795110/110798409-24b48a80-8248-11eb-864b-66a4e2edc1f3.png)

**Comment by bauagonzo** [comment]
Thanks @mikhailredis for the answer and for that project ;-)

That's my bad, I was expecting no data if there was no fresh point. But it works perfectly like that.

**Comment by mikhailredis** [comment]
@bauagonzo Thank you for the update. This is how we designed Streaming to always retrieve the most updated value.
