### ISSUE TITLE
Docker Unzip install giving Plugin health check failed

### ISSUE THREAD

**Issue by TylerAvocat** [RedisGrafana/grafana-redis-datasource#173]
### Describe the bug
I am using grafana with no internet install, meaning that I use the unzipping approach.

The docker grafana uses a binded volume: 
"/opt/docker/binded_volumes/grafana_stack/plugins/:/var/lib/grafana/plugins/"

In this directory I have the unzipped file https://grafana.com/api/plugins/redis-datasource/versions/1.3.1/download

Grafana starts as expected but when I try to add the data source I have a "Plugin health check failed"

When I start another grafana an do an internet install it all works fine.

I modified grafana log level to debug but id does not give much:
_t=2021-03-15T14:13:22+0000 lvl=dbug msg="Not adding CSP header to response since it's disabled" logger=http.server
t=2021-03-15T14:13:22+0000 lvl=dbug msg="Received command to update data source" logger=datasources url=redis://redis:6379
t=2021-03-15T14:13:22+0000 lvl=dbug msg="Applying default URL parsing for this data source type" logger=datasource type=redis-datasource url=redis://redis:6379
t=2021-03-15T14:13:22+0000 lvl=dbug msg="Not adding CSP header to response since it's disabled" logger=http.server
t=2021-03-15T14:13:22+0000 lvl=dbug msg="Not adding CSP header to response since it's disabled" logger=http.server
t=2021-03-15T14:13:22+0000 lvl=dbug msg="Not adding CSP header to response since it's disabled" logger=http.server
t=2021-03-15T14:13:22+0000 lvl=dbug msg="Querying for data source via SQL store" logger=datasources id=12 orgId=1
t=2021-03-15T14:13:22+0000 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="failed to check plugin health: health check failed" remote_addr=10.0.65.4_

### Version
redis-datasource 1.3.1
grafana 7.4.1

### Expected behavior
Should work or at least give a more descriptive message

**Comment by mikhailredis** [comment]
Hello @TylerAvocat, thank you for submitting the issue.

I believe this error means that Grafana can't execute data source's executable for your platform. Do you see any other errors?

Could you please check that +x is set for redis-datasource_linux file using `ls -l /var/lib/frafana/plugins` inside the Docker container and let me know.

**Comment by TylerAvocat** [comment]
You're right, it is a permission issue. I took me a while to get there from the "Plugin health check failed" message.

I am all good now, thanks for you help.

**Comment by mikhailredis** [comment]
@TylerAvocat Thank you for the update. I will add it to the documentation.

**Comment by mikhailredis** [comment]
Documented in [Quickstart](https://redisgrafana.github.io/quickstart/#install-without-internet-access) page.
