### ISSUE TITLE
Extract Timestamp from Redis Stream Entry id

### ISSUE THREAD

**Issue by bmsan** [RedisGrafana/grafana-redis-datasource#174]
### Extract timeseries information from Redis Stream
By default(if not explicitly set by the user) the automatically generated Redis [Stream](https://redis.io/topics/streams-intro) Entry ids contain insertion time information. 
`<millisecondsTime>-<sequenceNumber>`
This information could be useful in grafana as a timesource.

### I've created a fork in which I am extracting this information and sending it to grafana as an extra column of type time.Time
https://github.com/RedisGrafana/grafana-redis-datasource/compare/master...bmsan:master
(I still need to add some safety checks such that the plugin doesn't crash if for any reason  the Entry ids are in another format).

Using the code above I can correctly view the data in table view.
If you would like me to open a PR after I add the extra safety check please tell me.

### What still puzzles me (and maybe I should open a separate question ticket for this)
(Please keep in mind that my overall Grafana experience is summed up to a few hours today.)
I wasn't able to switch from Table view to actual visualizations("Unable to graph data"), when the streaming option in the Grafana plugin is disabled and I bring a batch of entries(using XREVRANGE & COUNT > 1)
![image](https://user-images.githubusercontent.com/52523668/111175514-2b792f80-85b1-11eb-9603-1e3c9027732b.png)

![image](https://user-images.githubusercontent.com/52523668/111175883-827f0480-85b1-11eb-9f95-3bcd7c463678.png)

**Comment by mikhailredis** [comment]
@bmsan Great idea! Please open PR to add it to the upcoming release.

Regarding visualize as Graph, let me check.

**Comment by mikhailredis** [comment]
@bmsan I updated the time field adding checks and also fixed tests. Could you please allow me to push updates to your branch?

Regarding visualize as Graph, stream fields returned as strings in the current implementation:
```
		for i := 0; i < len(keyValuePairs); i += 2 {
			key := string(keyValuePairs[i].([]byte))
			value := string(keyValuePairs[i+1].([]byte))

			// Check if field has been already created before
			if _, ok := fields[key]; !ok {
				// Create new field
				newField := data.NewField(key, nil, []string{})
				fields[key] = newField

				// Append field to frame
				frame.Fields = append(frame.Fields, newField)

				// Get the number of rows we processed previously
				rowsCount := idField.Len() - 1

				// Generate empty values for all previous rows
				for j := 0; j < rowsCount; j++ {
					newField.Append("")
				}
			}

			// Insert value for current row
			fields[key].Append(value)
			keysFoundInCurrentEntry[key] = true
		}
```

To display it on the Graph, the value should be checked if it's a float and use correct type similar to:
```
		if floatValue, err := strconv.ParseFloat(value, 64); err == nil {
			frame.Fields = append(frame.Fields, data.NewField(fields[i], nil, []float64{floatValue}))
		} else {
			frame.Fields = append(frame.Fields, data.NewField(fields[i], nil, []string{value}))
		}
```

We can do it in the next PR after adding the `time` field.
Thank you!

**Comment by TylerAvocat** [comment]
Hello, I was trying to display a STREAM in a graph using redis-datasource 1.3.1, I guess from this ticket that it is not possible. Let me now if there is a beta build for 1.4 that I can use to test this feature once it is implemented!

**Comment by bmsan** [comment]
@mikhailredis Thank you for looking into this so fast!
I have sent you a an invitation for direct access to the repo.
Just some thoughts that popped up in my head:

Related to naming:
> 1. Does it matter to grafana the exact name we give the time field? 
> If not maybe it would be good for us to avoid `time` since it might exist in the user defined keys. Maybe something like `$time`?
> 2. Assuming the answer to "1" is we can give it any name we want, would we also want in the future to convert user defined keys like "time" or "timestamp" to time.Time as well? Also what would happen if multiple fields would be of type time.Time. Would it be possible to decide which one to use as a timebase?


- Related to datatypes:
3.  I also was inclined to try to convert the values from string to Float, but I assumed that it wouldn't work because if I used XREVRANGE with COUNT=1 & streaming enabled the graphs would show.  Does that mean that for the streaming usecase somewhere in the code a conversion is already taking place?
4. In the long run maybe it would be helpful(but again my experience with Grafana is limited) for the user to be able to define in the UI a list of keys and associated datatypes which would get back to this plugin to be used for data conversion strategies? (This applies only if there are other types of interest for Grafana besides float and string(one example would be time) ) 

- Random Redis & Grafana(I can open a different question ticket if you want):
It would have been extremely cool to be able to select for a single query/data source multiple visualizations(possible of different types). 
Eg: let's say I have a query which returns timestamp, diskspace and latency.
It would be useful to be able to see two non overlapping plots in two windows (timestamp vs diskspace and in a different window timestamp vs latency) .
Maybe this is possible but my limited understanding is that I would have to do two different queries for each window, so I would end up bringing the same data two times.
I am not sure if this is related to the redis-datasource plugin or to Grafana in general (or even if m

**Comment by mikhailredis** [comment]
@bmsan Thank you for contributing! PR accepted and merged to master.

1. Done, having time as `$time` makes sense similar to `$streamId`, and the field's name does not matter.
2. It depends on the use case, but you should not store timestamps in streams. I would recommend separating streams in this case.
3. Done for XRANGE and XREVRANGE commands in the same PR. Correct, streaming checking it separately and it's working as expected.
4. It should be done with Type Transformations, which is in Grafana's roadmap.

Thank you for the questions and suggestions.

**Comment by mikhailredis** [comment]
@bmsan Please take a look at the Redis Dashboard, which is a part of the Redis Data Source, for example.

You can choose `Dashboard` as source Datasource and then select query:
![Screen Shot 2021-03-16 at 2 19 50 PM](https://user-images.githubusercontent.com/47795110/111360090-b6663280-8662-11eb-981b-ad99afdb07c6.png)

Please let me know if there is anything else.

**Comment by mikhailredis** [comment]
@TylerAvocat @bmsan You are welcome to try the nightly build with the new feature and let me know if it works for you:

```
docker run -p 3000:3000 --name=redis-app ghcr.io/redisgrafana/redis-app:latest
```

Here are examples streaming and non-streaming for XRANGE and XINFO command:

![Screen Shot 2021-03-16 at 2 38 59 PM](https://user-images.githubusercontent.com/47795110/111362694-80767d80-8665-11eb-9454-4a15e21402c4.png)

**Comment by bmsan** [comment]
@mikhailredis This is great. Thank you for the extremely quick turnaround  and for having the patience to respond to all my questions!

**Comment by mikhailredis** [comment]
@bmsan Let me know if there is anything else and I would like to see your project with dashboards when it's ready.

**Comment by TylerAvocat** [comment]
@mikhailredis @bmsan, thanks for this new feature.

I am trying the nighly build and I can now see the time field and another field I have called ''localization_uuid" in a table. Could you tell me how to get to the graph vizualisation ? I usually use the time interval filtering with other datasource but I guess it has to be achieved by some other means here.

![Screenshot from 2021-03-17 11-09-08](https://user-images.githubusercontent.com/3041663/111451081-58dcef00-8711-11eb-8512-18b0f4523a2e.png)
![Screenshot from 2021-03-17 11-09-23](https://user-images.githubusercontent.com/3041663/111451133-672b0b00-8711-11eb-9158-a0552d735156.png)

Thanks four your help.

**Comment by mikhailredis** [comment]
@TylerAvocat To get Graph Visualizing your fields should contain numbers. `localization_uuid` is a string and can't be displayed on the graph. You can try to use the `Group By` transformation to get the count. Let me know if it works.

XRANGE command use filtering by IDs, I think we can construct ID based on the Grafana time-range - I will open a feature request.

**Comment by TylerAvocat** [comment]
I could get where I wanted using the Group By approach:
![Screenshot from 2021-03-17 15-00-00](https://user-images.githubusercontent.com/3041663/111479766-9487b100-8731-11eb-9bcd-a3e9da0120af.png)
Thanks for your help @mikhailredis
