### ISSUE TITLE
Plugin healtcheck failed

### ISSUE THREAD

**Issue by cardosocristian** [RedisGrafana/grafana-redis-datasource#178]
I am running graphana 7.1.3 and installed the redis data source plugin to use the dashboard that you provide.
My redis server runs on an Almalinux8 / Centos 8 server and my grafana runs on another FreeBSD server.

![image](https://user-images.githubusercontent.com/32941615/112370285-f1e4aa80-8cbb-11eb-894e-d0e6855271b2.png)

I can telnet to the redis server on port 16379
```
# telnet 10.19.254.5 16379
Trying 10.19.254.5...
Connected to 10.19.254.5.
Escape character is '^]'.
```

I also checked that the database is zero
```
# redis-cli INFO | grep ^db
db0:keys=21292791,expires=21292791,avg_ttl=29724405
```

Follows plugin log:

t=2021-03-24T16:10:21-0300 lvl=eror msg="Plugin health check failed" logger=context userId=2 orgId=1 uname=cristian.cardoso error="Failed to check plugin health: Health check failed" remote_addr=10.7.8.243
t=2021-03-24T16:10:21-0300 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=cristian.cardoso method=GET path=/api/datasources/16/health status=500 remote_addr=10.7.8.243 time_ms=12 size=40 referer=http://zabbix-net.local.net:3000/datasources/edit/16/

**Comment by mikhailredis** [comment]
Hello @cardosocristian. This error means that Grafana can't execute the `redis-datasource` binaries. Did you install Redis Data Source using `grafana-cli` or extracted manually?

**Comment by cardosocristian** [comment]
I installed it via the command mentioned on the graphana website.

```
# grafana-cli plugins install redis-datasource
installing redis-datasource @ 1.3.1
from: https://grafana.com/api/plugins/redis-datasource/versions/1.3.1/download
into: /var/db/grafana/plugins

✔ Installed redis-datasource successfully
```

Is there any kind of limitation when graphana is in FreeBSD?

**Comment by cardosocristian** [comment]
I configured the version available in pkg and it is now in version 7.3.4, I ran the command to use the plugin again and the same error persists

**Comment by mikhailredis** [comment]
@cardosocristian Any specific reason, why do you run Grafana on the FreeBSD server? Grafana plug-in platform does not support `FreeBSD` platform and no binaries compiled for it. All supported platforms are:

```
% ls -l *datasource*
-rwxr-xr-x  1 mikhail  staff  13806272 Mar 20 11:20 redis-datasource_darwin_amd64
-rwxr-xr-x  1 mikhail  staff  12644352 Mar 20 11:20 redis-datasource_linux_amd64
-rwxr-xr-x  1 mikhail  staff  10682368 Mar 20 11:20 redis-datasource_linux_arm
-rwxr-xr-x  1 mikhail  staff  11796480 Mar 20 11:20 redis-datasource_linux_arm64
-rwxr-xr-x  1 mikhail  staff  13077504 Mar 20 11:20 redis-datasource_windows_amd64.exe
```

I am checking with the Grafana SDK team what is the plans to support the FreeBSD platform, but, unfortunately, it's not supported in the latest version.

**Comment by cardosocristian** [comment]
It is the server where my zabbix-server already runs, it was the natural way to install grafana on it, until now this was the first plugin that did not work on FreeBSD.
Another factor that makes me use FreeBSD is stability, as well as the ability to upgrade without breaking libraries as occurs with most Linux distributions that support upgrading.

**Comment by mikhailredis** [comment]
Unfortunately, Grafana does not officially support FreeBSD for Backend Plugin SDK and there is not enough interest to add it.
This limitation mentioned in the documentation: http://localhost:8000/redis-datasource/overview/#supported-platforms.
Closing.
