### ISSUE TITLE
RedisTimeSeries TS.MGET support

### ISSUE THREAD

**Issue by filipecosta90** [RedisGrafana/grafana-redis-datasource#192]
### Is your enhancement related to a problem? Please describe.

It's usual to use the same type of queries of TS.MRANGE but to want only the last sample of each serie that matches the filter. 
Example usage:
Get me the last result for each product version ( instead of the average or max/min given that for those aggregations we have MRANGE).

### Additional context
 TS.MGET api reference: https://oss.redislabs.com/redistimeseries/commands/#tsmget
```
TS.MGET [WITHLABELS] FILTER filter...
```

PS: @mikhailredis will very gladly open the PR supporting it. Please share your toughts on it.

**Comment by mikhailredis** [comment]
@filipecosta90 please send PR and I will include it in the upcoming release.
