### ISSUE TITLE
Can't get number as Grafana variable

### ISSUE THREAD

**Issue by Severin-S** [RedisGrafana/grafana-redis-datasource#205]
### Describe the bug
Trying to set a Grafana variable to the value of a Redis key fails with the following error if the value only contains digits.
>Validation 
>Cannot use 'in' operator to search for 'fields' in NaN
>
>Templating [query0]
>Error updating options: Cannot use 'in' operator to search for 'fields' in NaN

### Version
Grafana version 7.5.5
Redis plugin version 1.4.0

### Steps to reproduce
1. Execute `SET tmp "1"` in Redis
1. Create a new Dashboard in Grafana
1. Add a variable
1. Set `GET tmp` as query

Setting `tmp` to `1` instead of `"1"` leads to the same error. When adding any non digit (e.g. `"1 "`) to the string, the error does not occur.

### Expected behavior
The Grafana variable should be set to the value of the Redis key regardless wether it only contains digits or not.

### Screenshots
![image](https://user-images.githubusercontent.com/26414182/122885774-ad5ebe80-d33f-11eb-8e8f-20fb689fd597.png)

**Comment by mikhailredis** [comment]
@Severin-S thank you for reporting the issue. If the string contains a number, then it's converted to a number for graphs. Unfortunately, I have not tried it for variables recently, using strings in variables for my projects. 
I will check how to fix it and get back to you shortly.

**Comment by mikhailredis** [comment]
@Severin-S the issue is fixed for Grafana 7. Grafana 8 returns result differently and work without the fix.
You can test using the latest Docker build: https://redisgrafana.github.io/development/images/
I am planning to release version 1.5.0 with the fix over the weekend.
