### ISSUE TITLE
How to read binary string key ? We using kryos to serizal string key to byte array

### ISSUE THREAD

**Issue by cdc007** [RedisGrafana/grafana-redis-datasource#215]

**Comment by mikhailredis** [comment]
@cdc007 Could you please provide more information on your use case.
Do you want to display this string key in the panel?

**Comment by cdc007** [comment]
I want display string key in plane

**Comment by cdc007** [comment]
Close the ticket by accident .could u reopen it

**Comment by cdc007** [comment]
Because if using kryos do  serialize . Insert byte array. In grafana panel not readable.

**Comment by mikhailredis** [comment]
@cdc007 Are you talking about https://github.com/EsotericSoftware/kryo project?
Do you mind sending me a sample rdb file with the serialized keys to take a look at?

**Comment by cdc007** [comment]
Hey I am out of town currently. Yes that kryo project is the one which being used by lots of company.actually you can simple use kryo api to serialize a string  to binary and insert to redis. U will find the in grafana string can't read .  .

**Comment by cdc007** [comment]
Sry out of town. Just using java kryos to serialize a string key to byte array then hmset to redis. U will find key are binary format which hard to read in grafana panel.  Is there a plug in or still can out deserialize byte array to string before render to user? Only simple strong not complicate other?java objects

**Comment by cdc007** [comment]
Hello any update?

**Comment by mikhailredis** [comment]
@cdc007 There is no javascript/typescript implementation for kryo serializer as I understand. To implement the panel which can show the object from the Redis cache string we have to implement a deserializer, which is hard to do because it's not documented properly and it's out of the scope for Redis plugins.

Let me know if you know of a better solution.

**Comment by mikhailredis** [comment]
@cdc007, please let me know if there is anything else.
Closing for now.
