### ISSUE TITLE
"Plugin unavailable" for Redis-Datasource (or Redis-App) Plugin on s390x machine.

### ISSUE THREAD

**Issue by kycfeel** [RedisGrafana/grafana-redis-datasource#216]
### Describe the bug
Redis-Datasource (or Redis-App) Plugin for Grafana doesn't function on the s390x machine due to the "Plugin unavailable" error.

This is the error I got from console:

```
2021-09-14T06:40:38+0000 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=redis-datasource error="fork/exec /var/lib/grafana/plugins/redis-datasource/redis-datasource_linux_s390x: no such file or directory"

t=2021-09-14T06:41:54+0000 lvl=eror msg="Plugin unavailable" logger=context userId=1 orgId=1 uname=bitholla error="plugin unavailable" remote_addr=218.144.134.67

t=2021-09-14T06:41:54+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=bitholla method=GET path=/api/datasources/5/health status=503 remote_addr=218.144.134.67 time_ms=377 size=32 referer=https://<MY_GRAFANA_URL>/datasources/edit/5
```

### Version
- Grafana v7.5.3

### Steps to reproduce
Install `redis-datasource` or `redis-app` plugin through the `GF_INSTALL_PLUGINS` env.

### Expected behavior
Everything works fine with no issue.

### Screenshots
-

### Additional context
I think there's a chance that the pre-built binary for redis-datasource does not exist for the s390x machines.

**Comment by mikhailredis** [comment]
Hello @kycfeel, unfortunately, Grafana Plugins SDK does not support s390x architecture.
Please take a look at the supported platforms in the documentation: https://redisgrafana.github.io/redis-datasource/overview/#supported-platforms
Let me know if there is anything else.

**Comment by mikhailredis** [comment]
@kycfeel, please let me know if there is anything else.
Closing for now.
