### ISSUE TITLE
When the new Redis will be released to be compatible with Grafana v8.2.1 ?

### ISSUE THREAD

**Issue by ermalbaj** [RedisGrafana/grafana-redis-datasource#222]

**Comment by mikhailredis** [comment]
@ermalbaj Let me know if you have any questions.
I am finishing version 2.0 and release it later this week.

**Comment by ermalbaj** [comment]
Tested and everything is working fine.
Thank you for the release.

**Comment by mikhailredis** [comment]
@ermalbaj, thank you for confirming.

Please let me know if there is anything else.
