### ISSUE TITLE
SCARD does not show a key field any more

### ISSUE THREAD

**Issue by BSVogler** [RedisGrafana/grafana-redis-datasource#233]
### Describe the bug
The SCARD command needs a key field. It is even displayed in the documentation.
https://redisgrafana.github.io/redis-datasource/redis/SCARD/

### Version
redis plug in 1.5.0
Grafana 8.2.0

### Steps to reproduce
Create new panel. Add new query.

### Expected behavior
Should show a key field.

### Screenshots
<img width="1259" alt="Bildschirmfoto 2021-11-10 um 12 26 14" src="https://user-images.githubusercontent.com/801818/141104910-7352846b-41bf-40a7-bdd6-a7bac7daebeb.png">

**Comment by mikhailredis** [comment]
@BSVogler, thank you for opening the issue.
Fixed and will be released in v2.0.0 today.
