### ISSUE TITLE
Connection refused in cluster mode

### ISSUE THREAD

**Issue by sylvainv** [RedisGrafana/grafana-redis-datasource#235]
### Describe the bug

We are trying to connect to our Redis Cluster within our VPC. The grafana is also deployed within the vpc, on AWS ECS.
I tried several inputs:

* 172.22.1.19:6379,172.22.2.25:6380,172.22.0.89:6381
* redis://172.22.1.19:6379,172.22.2.25:6380,172.22.0.89:6381
* redis://172.22.1.19:6379,redis://172.22.2.25:6380,redis://172.22.0.89:6381

All of those input report:

```
getInstance error: error connecting to 127.0.0.1:6381: dial tcp 127.0.0.1:6381: connect: connection refused
```

While localhost is not even on the provided list of servers. All connections work individually. Ports are opened correctly.

### Version

Grafana v8.0.4 (81fef5b4b4) 
Version 1.5.0
Deployed on AWS ECS

### Steps to reproduce

1. Create a Redis Datasource
2. Create a Redis Cluster on a same network as the grafana instance
3. Input the URLS to the cluster instances
4. Click save and test 

### Expected behavior

We should see all green and connected.

**Comment by mikhailredis** [comment]
@sylvainv, could you please run `CLUSTER NODES` to check the cluster nodes with their IP addresses.
Redis client when connecting to Redis cluster node receives the IP address from the Cluster and then connects to each node using returned IP.

**Comment by sylvainv** [comment]
```
ec12bfbcd5b91a30c0db723c10d6c531b6e411a4 172.22.1.19:6379@16379 master - 0 1637240503499 1 connected 0-5460
1cd543d22290ed50d3ef66e9cb4f45c616316ec9 172.22.1.19:6381@16381 slave 65b613f7ad31362b955ae9801f582cf8f51cdc69 0 1637240501493 3 connected
0c59911df480442bae9d9b950e24784ec2f3a97d 127.0.0.1:6380@16380 slave c5840cb9753fb0607155b5c5c849a033fc4cd3e5 0 1637240501000 2 connected
458db065a2f9784d468efc1e261b466025788678 172.22.2.25:6379@16379 slave ec12bfbcd5b91a30c0db723c10d6c531b6e411a4 0 1637240502000 1 connected
65b613f7ad31362b955ae9801f582cf8f51cdc69 172.22.0.89:6381@16381 myself,master - 0 1637240498000 3 connected 10923-16383
c5840cb9753fb0607155b5c5c849a033fc4cd3e5 172.22.2.25:6380@16380 master - 0 1637240502497 2 connected 5461-10922
```

@mikhailredis

**Comment by mikhailredis** [comment]
@sylvainv, I will set up a test OSS Redis cluster on multiple nodes and will try to reproduce the issue to investigate further.
I will get back to you shortly.

**Comment by sylvainv** [comment]
@Izual750 is also working on this issue and can take over if necessary @mikhailredis

**Comment by sylvainv** [comment]
Hello @mikhailredis any update on the issue?

**Comment by mikhailredis** [comment]
@sylvainv, I have verified the plugin and set up demo environment for future development: https://demo.volkovlabs.io/d/TTQkU657k/redis-cluster

![Screen Shot 2021-11-19 at 4 13 02 PM](https://user-images.githubusercontent.com/47795110/142694415-469e1088-1baa-4e11-a2ba-ff2a052ea03e.png)

I believe I know your issue. Looking at the `CLUSTER NODES` output, one of your nodes set at `127.0.0.1`. All of the nodes should be defined with their IP address available from the Grafana instance.

Please let me know if it helps.

**Comment by Izual750** [comment]
Thanks ! 

I'll modify the config actually, the nodes are configured to listen both on the "private IP" network interface and loopback.

I'll modify everything to listen on private interface only and retry :)

**Comment by mikhailredis** [comment]
@Izual750, please keep me updated with your progress.

**Comment by Izual750** [comment]
Everything's good now 👍
 Thanks for your help 🙂

**Comment by mikhailredis** [comment]
@Izual750, thank you for the update. Documentation updated to avoid this issue in the future: https://redisgrafana.github.io/redis-datasource/faq/

Please let me know if there is anything else.

**Comment by Izual750** [comment]
Thanks for the update of the doc :)

The confusing thing for me was that, if I have a bind address like this:
```
bind 192.168.1.100 172.16.10.50
```

I can have a node endpoint like this:
- **Endpoint 1:** 192.168.1.100 
```
ec1... 192.168.1.100:6379@16379 master - 0 1637240503499 1 connected 0-5460
```
- **Endpoint 2**: 172.16.10.50
```
ec1... 172.16.10.50:6379@16379 master - 0 1637240503499 1 connected 0-5460
```
 
And if the Grafana Redis-cluster datasource plugin is configured to use `192.168.1.100`, _It seems_ I have no way to anticipate that redis-cluster will not tell the datasource plugin to redirect its requests on `172.16.10.50`.

But in my case, `172.16.10.50` security group was blocking the connection from 192.168.1.0/24, so the request fails.

Can you explain me a bit what's the behavior of the Plugin in this specific case? :x

**Comment by mikhailredis** [comment]
@Izual750, let me clarify:
1) Redis client in Cluster mode will try to connect to any available node specified in the Address.
2) When client connects it retrieves all cluster nodes information and key slots.
3) When plugin request specific keys from the client, client already knows which node has the key based on the slot and send the request to this node.

You can't tell the other node in the cluster to respond for other node's key if this is the questions. To access the specific node information, you should connect all nodes as Standalone.

Please take a look at the Cluster specification for details, https://redis.io/topics/cluster-spec.

Let me know if there is anything else.

**Comment by Izual750** [comment]
Ok I see !

Thanks for the explanation it's very clear :smile:
