### ISSUE TITLE
getInstance error: dial tcp ec2-xx-xxx-xxx-xxx.us-east-2.compute.amazonaws.com:6379: i/o timeout

### ISSUE THREAD

**Issue by OjerDev** [RedisGrafana/grafana-redis-datasource#236]
My Redis server running in a Linux environment. I am trying to connect my Redis data source to the Grafana dashboard. While I am connecting I am facing this error.

Error: getInstance error: dial tcp ec2-xx-xxx-xxx-xxx.us-east-2.compute.amazonaws.com:6379: i/o timeout

Grafana is running on **windows machine**

**Comment by mikhailredis** [comment]
@OjerDev, `i/o timeout` error in most cases means it's a firewall issue.
Are you able to connect from Windows machine to the Redis database running on the Linux instance in AWS using `redis-cli` or any other tool like `telnet`? If not, then you need to add the firewall rule for the Linux instance.

**Comment by OjerDev** [comment]
@mikhailredis First of all thanks for the quick response. 
I have tried to connect Redis DB (Linux instance) from my windows machine. I am getting the following error:

**C:\Users>****redis-cli -h ec2-xx-xxx-xxx-xx.us-east-2.compute.amazonaws.com -p 6379**
_Could not connect to Redis at ec2-xx-xxx-xxx-xx.us-east-2.compute.amazonaws.com:6379: Unknown error
not connected_

C:\Users>**telnet ec2-x.x.x..us-east-2.compute.amazonaws.com**
Connecting To ec2-x.x.x.x.us-east-2.compute.amazonaws.com...Could not open connection to the host, on port 23: Connect failed.

But I have opened the **ssh -22 port and custom TCP port 6379** in the inbound group rule of the instance security group.

**Comment by mikhailredis** [comment]
@OjerDev, if you can't connect using `redis-cli` or `telnet`, it's a connectivity issue.

Check `iptables -L` on the host, it may block incoming connections. Do you run Redis in the container or Linux host itself?

**Comment by mikhailredis** [comment]
@OjerDev, please keep me updated with your progress.

**Comment by OjerDev** [comment]
@mikhailredis  I am running the redis as a Linux host. Not using docker container.  This is my status of "iptables -L" 

I am new to the Linux environment. I have just pasted the output of iptables -L 

root@ip-xxx-xx-xx-xxx:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (0 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION-STAGE-1 (0 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION-STAGE-2 (0 references)
target     prot opt source               destination

Chain DOCKER-USER (0 references)
target     prot opt source               destination

Chain ufw-after-forward (0 references)
target     prot opt source               destination

Chain ufw-after-input (0 references)
target     prot opt source               destination

Chain ufw-after-logging-forward (0 references)
target     prot opt source               destination

Chain ufw-after-logging-input (0 references)
target     prot opt source               destination

Chain ufw-after-logging-output (0 references)
target     prot opt source               destination

Chain ufw-after-output (0 references)
target     prot opt source               destination

Chain ufw-before-forward (0 references)
target     prot opt source               destination

Chain ufw-before-input (0 references)
target     prot opt source               destination

Chain ufw-before-logging-forward (0 references)
target     prot opt source               destination

Chain ufw-before-logging-input (0 references)
target     prot opt source               destination

Chain ufw-before-logging-output (0 references)
target     prot opt source               destination

Chain ufw-before-output (0 references)
target     prot opt source               destination

Chain ufw-reject-forward (0 references)
target     prot opt source               destination

Chain ufw-reject-input (0 references)
target     prot opt source               destination

Chain ufw-reject-output (0 references)
target     prot opt source               destination

Chain ufw-track-forward (0 references)
target     prot opt source               destination

Chain ufw-track-input (0 references)
target     prot opt source               destination

**Comment by mikhailredis** [comment]
@OjerDev, I don't see any blocking rules on the Linux instances. It may be another firewall in-between which blocking connection. You have to check your environment and verify it step by step.

Let me know if you have any questions.

**Comment by mikhailredis** [comment]
@OjerDev, please let me know if you able to resolve the issue or require further assistance.

**Comment by mikhailredis** [comment]
@OjerDev, let us know if you need anything else.
