### ISSUE TITLE
Grafana template variables not working for the Default datasource

### ISSUE THREAD

**Issue by ngleader** [RedisGrafana/grafana-redis-datasource#242]
### Describe the bug

can not load template variables by redis query.

### Version

- grafana 8.1.0, 8.3.0
- redis-datasource 2.0.0

### Steps to reproduce
1. setup redis datasource
2. create redis sets item & add value
3. make grafana template variable with query "smembers mykey" or "get mykey2"
4. Preview of values : None => not working

### Additional context

![image](https://user-images.githubusercontent.com/199256/144526317-deccc6a6-d47b-4450-bd87-2c81508265d2.png)

**Comment by mikhailredis** [comment]
@ngleader, do you see any errors in the Browser Console?

Are you able to create a panel with the `get` or `smembers` command and display values on your dashboard?

I will check on my test environment.

**Comment by mikhailredis** [comment]
@ngleader, I remember 8.1.X had issues with loading Variables for Default Data Source, which was fixed in 8.2.X. Let me check what happened in 8.3.0.

**Comment by mikhailredis** [comment]
@ngleader, I just tested on the 8.3.0 and everything is working as expected.

Please let me know if you see any issues in the Browser Console.

**Comment by ngleader** [comment]
@mikhailredis 

# datasource
![image](https://user-images.githubusercontent.com/199256/144739755-7689a140-08ac-4ce5-9f8d-c18978ec2c97.png)

# test smembers
![image](https://user-images.githubusercontent.com/199256/144739686-dc0425bd-4eb7-46c6-81ef-3cd66e38bf03.png)

# setting variables
![image](https://user-images.githubusercontent.com/199256/144739816-c2e05a66-f45e-4d6c-8d8c-016724934dcd.png)
![image](https://user-images.githubusercontent.com/199256/144739835-69550b92-e91e-4bd8-a87f-14686952a042.png)

# my redis plugin
![image](https://user-images.githubusercontent.com/199256/144739856-710be614-ad44-4ce6-9d4b-e9a1a7535210.png)

![image](https://user-images.githubusercontent.com/199256/144739922-f5e8af1f-2883-4af9-9154-dd9216aa9f9d.png)


# version
redis cluster(redis 6.2.6)
![image](https://user-images.githubusercontent.com/199256/144739701-5b60fa89-0b1d-4d65-84a9-d02964a57051.png)
![image](https://user-images.githubusercontent.com/199256/144739725-bda5e872-ca95-4477-b7e8-b76abff9cdf3.png)

**Comment by mikhailredis** [comment]
@ngleader It's the same issue with variables when the data source is set as `Default`. I just reproduced the issue on 8.3.0.

Could you please unset 'Default' and it should work as expected?

I will check the code and investigate with the Grafana team if necessary.

**Comment by mikhailredis** [comment]
@ngleader Thank you for opening the issue. The bug is fixed and will be a part of the upcoming release.
Meanwhile, variables should work for the Redis data source not marked as Default.

Please let me know if there is anything else.
