### ISSUE TITLE
How to display a Grafana table using redis?

### ISSUE THREAD

**Issue by vgoklani** [RedisGrafana/grafana-redis-datasource#259]
We would like to display a "table" (multiple columns/rows) in grafana, and store the data in redis... :)

We're flexible on the schema, but currently storing rows as JSON encoded strings in a redis hash. 

What's the best way of doing this? Our goal is to just have one backend, and we're obviously choosing redis because it's so simple and easy to use.

We also feel that this is a very common use case (displaying tabular data in grafana) so there should be simple solution.

Thank you!

**Comment by mikhail-vl** [comment]
@vgoklani There are multiple ways to display data in a table. One of the options will be to use RedisJSON to store you JSON encoded strings.

You can learn more in the documentation: https://redisgrafana.github.io

**Comment by agmvilla** [comment]
Might you have any example on how to extract the value from the json field in a redis key?
I fighting on trying to make it work here, but I could not find any clear documentation/example on how to do that.
Thanks!

**Comment by mikhail-vl** [comment]
@agmvilla Are you asking about RedisJSON or `string` with JSON inside?

  There is a `Extract Data` transformation. Have you tried it?

**Comment by agmvilla** [comment]
Hi I'm talking about RedisJson, but finally I got it woking :-)
Thanks for your reply.

**Comment by slorello89** [comment]
going to close to tidy up and it seems the op has not responded. feel free to reopen if needed.
