### ISSUE TITLE
So many timeouts!!!!

### ISSUE THREAD

**Issue by vgoklani** [RedisGrafana/grafana-redis-datasource#261]
Hey there,

We're using Grafana + Redis Timeseries - with *lots* of dashboards and panels...

We're seeing a lot of timeouts on Grafana, and wondering how to best address this? 

Are the requests being pipelined to Redis based on the dashboard and/or panel? 

How do we see the logs on redis for each of these requests?

Thanks!

**Comment by mikhail-vl** [comment]
@vgoklani I would recommend to increase the Pool Size to see if it helps: https://redisgrafana.github.io/redis-datasource/configuration/#pool-size

**Comment by vgoklani** [comment]
thanks @mikhail-vl 

Could you please explain the "Pipeline WIndow":

    Sets the duration in microseconds after which internal pipelines will be flushed. If window is zero then implicit pipelining will be disabled. Default value is 0.

What pipeline are we talking about, i.e. is this the redis pipeline? How should we tune this?

**Comment by mikhail-vl** [comment]
The Pipeline Window option is unpredictable and not well tested - it's Redis pipeline. Various Grafana panels will use pool of connections with Redis pipeline and you can't really predict which requests goes where.
I would not touch it and just increase the pool size.

**Comment by vgoklani** [comment]
got it, thanks!
