### ISSUE TITLE
STD.P STD.S Var.P and Var.S don't appear on RedisTimeSeries aggregation field

### ISSUE THREAD

**Issue by gtsaito** [RedisGrafana/grafana-redis-datasource#262]
STD.P STD.S Var.P and Var.S don't appear as an option under the aggregation field when building a query for RedisTimeSeries.
From the RedisTimeSeries documentation there should be (min, max, avg, sum, range, count, first, last, STD.P, STD.S, Var.P, Var.S) as options. 
I can aggregate with all these on the CLI and it works fine.

Grafana 8.4.4
RedisGrafana 2.1.1

![image](https://user-images.githubusercontent.com/12435843/167722513-5193949a-5f6c-4038-84a7-327a0b065a8e.png)

**Comment by mikhail-vl** [comment]
@gtsaito There is a PR waiting for Redis team approval: https://github.com/RedisGrafana/grafana-redis-datasource/pull/260
