### ISSUE TITLE
Get All Keys with values.

### ISSUE THREAD

**Issue by zaid3tech** [RedisGrafana/grafana-redis-datasource#263]
Hope you all doing good, Is there any way to query all keys with their data in tabular form like this?
```
Keys         Values
-------| ------------
   
key1    |  1
key2    |  2
key3    |  3
```

**Comment by mikhail-vl** [comment]
@zaid3tech You can use LUA, RedisGears and Functions in the latest version of Redis.
In Data Source select custom command and it should be possible.

**Comment by zaid3tech** [comment]
@mikhail-vl  Thanks for help, I will learn about it

**Comment by slorello89** [comment]
going to close to tidy up as the question appears to have been answered.
