### ISSUE TITLE
can't add redis cluster in datasource - getInstance error: cannot decode redis array into string

### ISSUE THREAD

**Issue by Nurlan199206** [RedisGrafana/grafana-redis-datasource#271]
grafana: 9.0.5
redis-datasource: 2.0.0

can't add 3 nodes redis cluster in datasource - error: getInstance error: cannot decode redis array into string

Address bar: 192.168.0.131:6379,192.168.0.132:6379,192.168.0.133:6379

![image](https://user-images.githubusercontent.com/22808731/185979682-49bb1583-39f0-4e79-8051-eee1f9447a3a.png)

**Comment by Nurlan199206** [comment]
also i tried use plugin version 2.1.1 but same error

**Comment by mikhail-vl** [comment]
@Nurlan199206 It looks like a connection issue to me, which was not parsed correctly.

What version of Redis do you use? Can you connect to all cluster nodes from the Grafana instance/container?

**Comment by Nurlan199206** [comment]
yes, if connecting to each node as `standalone` everything is ok, redis version `7.0.4`

![image](https://user-images.githubusercontent.com/22808731/187091704-170b9f65-5470-4200-a44a-4bc6d291671e.png)

![image](https://user-images.githubusercontent.com/22808731/187091730-bc6e89df-1549-44fc-9f7a-085744a95be4.png)

**Comment by mikhail-vl** [comment]
@mikhail-vl Redis 7 may changed the interface and the Radix client needs to be updated.

Let's wait for the Redis team response.

**Comment by hoangphuocbk** [comment]
I had the same issue with Redis cluster version 7.0.5

**Comment by mikhail-vl** [comment]
@K-Jo

**Comment by madhur** [comment]
I have the same issue. Any update?

**Comment by ikersuen** [comment]
I still met the same issue nowadays with latest version, any follow up?

**Comment by mikhail-vl** [comment]
@K-Jo There is a PR which waiting to merge https://github.com/RedisGrafana/grafana-redis-datasource/pull/284

**Comment by calvinlu3** [comment]
@mikhail-vl The PR has been open for some time now. When do you think the changes can be approved or is it still in progress?

**Comment by ikersuen** [comment]
Seems the merging is blocked for #284, any update for the fix?

**Comment by prat3033** [comment]
Same issues exists for me by when we can expect this Fix please.

**Comment by slorello89** [comment]
Closing as this should be resolved in v2.1.2

**Comment by tanvp112** [comment]
> Closing as this should be resolved in v2.1.2

The issue has re-surface: https://github.com/RedisGrafana/grafana-redis-datasource/issues/323
