### ISSUE TITLE
how to display the data got by hgetall which value is json into geomap

### ISSUE THREAD

**Issue by CuteSmartTiger** [RedisGrafana/grafana-redis-datasource#278]
## Summary
how to display the data got by hgetall which value is json into geomap

## Relevant information
first, i save my data in mysql . the table schema as follow
`
mysql> desc vehicle_location_state;
+--------------+--------------+------+-----+-------------------+-------+
| Field        | Type         | Null | Key | Default           | Extra |
+--------------+--------------+------+-----+-------------------+-------+
| vin          | varchar(50)  | NO   | PRI | NULL              |       |
| map_id       | varchar(32)  | YES  |     | NULL              |       |
| project_name | varchar(128) | YES  |     | NULL              |       |
| area_name    | varchar(128) | YES  |     | NULL              |       |
| location     | varchar(128) | YES  |     | NULL              |       |
| longitude    | double       | NO   |     | NULL              |       |
| latitude     | double       | NO   |     | NULL              |       |
| theta        | double       | NO   |     | NULL              |       |
| is_online    | int(11)      | NO   |     | NULL              |       |
| state        | int(11)      | NO   |     | NULL              |       |
| speed        | double       | NO   |     | NULL              |       |
| alert_info   | varchar(128) | YES  |     | NULL              |       |
| updated_ts   | datetime     | NO   |     | CURRENT_TIMESTAMP |       |
| created_ts   | datetime     | NO   |     | CURRENT_TIMESTAMP |       |
+--------------+--------------+------+-----+-------------------+-------+

`
second，i config the myql data source,use  **selec * from vehicle_location_state**
 the grafana can display the data in geomap.

now i need move the data to redis,but i meet the problem, grafana can not display the data in geomap.
it show one row on **Table view** event get  two  values  from redis.
my redis data as follow
`hgetall grafana:vehicle_location_state
1) "tb25nr.car111"
2) "{\"vin\":\"tb25nr.car111\",\"map_id\":\"223\",\"project_name\":\"",\"area_name\":\"\",\"location\":\"\",\"longitude\":110,\"latitude\":10,\"theta\":5.448169,\"is_online\":0,\"state\":0,\"speed\":0,\"alert_info\":\"\",\"updated_ts\":\"2022-11-15T18:10:03.113102905+08:00\",\"created_ts\":\"2022-11-15T18:10:03.113102968+08:00\"}"
3) "t30_22.car2"
4) "{\"vin\":\"t30_22.car2\",\"map_id\":\"223\",\"project_name\":\"",\"area_name\":\"",\"location\":\"",\"longitude\":10,\"latitude\":90,\"theta\":5.448169,\"is_online\":0,\"state\":0,\"speed\":0,\"alert_info\":\"\",\"updated_ts\":\"2022-11-15T18:13:13.133425844+08:00\",\"created_ts\":\"2022-11-15T18:13:13.133425907+08:00\"}"
`
i use grafana  to get the all field values by key grafana:vehicle_location_state, then i use **Transform**  to extract the json data, but
it need select the field,so it can not extract the all values at the same time.

What i home

**Comment by mikhail-vl** [comment]
@CuteSmartTiger You may need to use additional Transformation to convert it to the format GeoMap understands.

  Alternatively, you can take a look at the Apache ECharts Panel (https://github.com/volkovlabs/volkovlabs-echarts-panel), which can parse JSON and display using JSON or Baidu maps.
