### ISSUE TITLE
my redis cluster url is bad gateway

### ISSUE THREAD

**Issue by taeun0** [RedisGrafana/grafana-redis-datasource#279]
## Summary

I want to use Redis Explorer plugin(Redis Enterprise clusters). 
When I set my cluster url and port, an error message "Bad Gateway" is appeared.  
I set the same address in Redis Application plugin and it is running.
what should I do? Could you help me?..😿

### 1. Redis Application plugin cluster URL Information `(connected)`
<img width="500" alt="1" src="https://user-images.githubusercontent.com/59632881/202108694-f13bfd09-2c53-4d53-9d9f-a36fc73231f9.png">

### 2. Redis Explorer plugin cluster URL Information `(bad gateway)`
<img width="500" alt="2" src="https://user-images.githubusercontent.com/59632881/202108703-f3c2d9b9-52d6-4b0d-b651-9145465745a8.png">
<img width="500" alt="3" src="https://user-images.githubusercontent.com/59632881/202109218-e7b7dbca-cece-46f8-89fb-5894da87bd28.png">

**Comment by mikhail-vl** [comment]
@k-Jo

**Comment by taeun0** [comment]
@mikhail-vl @K-Jo
Is there any other way?

**Comment by nail-sirazitdinov** [comment]
Hi @taeun0 
Is your Redis Enterprise database OSS Cluster API enabled? If not, you should use a Standalone database connection.
For Explorer Redis Enterprise discovery mechanism, specify cluster FQDN (https://<cluster_fqdn>:9443) and admin credentials.
Please open a ticket in our support portal - https://support.redislabs.com/. The team will be glad to help.
Thank you

**Comment by nail-sirazitdinov** [comment]
@taeun0 let us know if you still need a hand with that one.

**Comment by 4n4nd** [comment]
@nail-sirazitdinov Could I please get some help with this? I have a Redis 7.0.4 cluster deployed on k8s. The grafana data source works fine if I use the standalone mode but doesn't work in cluster mode.

**Comment by nail-sirazitdinov** [comment]
@4n4nd is your grafana instance inside the same k8s cluster with Redis cluster or connecting via ingress? Are you able to connect your application to Redis in cluster mode connection (what is the redis library)? 
Is it [Redis Enterprise](https://docs.redis.com/latest/kubernetes/architecture/) k8s deployment or opensource?

**Comment by 4n4nd** [comment]
* The Grafana instance is inside the same k8s cluster communicating using a k8s service.
* I can connect to redis in cluster mode using the hiredis-cluster library.
* It is an opensource deployment

**Comment by nail-sirazitdinov** [comment]
@ollopaci ^^

What is the error, @4n4nd?

**Comment by 4n4nd** [comment]
Oh my bad I see a different error.
My error is `error: getInstance error: cannot decode redis array into string`

**Comment by 4n4nd** [comment]
@nail-sirazitdinov could you please update the radix dependency [here](https://github.com/RedisGrafana/grafana-redis-datasource/blob/v1.5.0/go.mod#L21) from `v3.7.0` to `v3.8.1`? I believe that should fix this connection issue.

**Comment by slorello89** [comment]
@4n4nd we just upgraded to v3.8.1 - waiting to go through the release process with Grafana now - keep an eye on #271 - I'll close that when the release goes out 

going to close this to tidy up as it seems to have gone dormant? Feel free to reopen if needed.
