### ISSUE TITLE
[Question] About JSON parsing using GET command

### ISSUE THREAD

**Issue by makarid** [RedisGrafana/grafana-redis-datasource#285]
## Summary
Hello, i save a json string to a Redis bucket which i can retrieve it using the GET command and then transform it using the "Extract fields". My issue is that the JSON string is a list of items (which should be rows on the grafana table) but instead they are displayed like columns with the names of 0,1,2,3... etc. Is it possible to parse the json string so that these items on the list to be displayed like rows and not columns? Alternatively, what json syntax i need to use in order to display a list in json string as rows and not as columns. Thank you

**Comment by slorello89** [comment]
Hi @makarid could you use `JSON.SET`/`JSON.GET`?:

```
JSON.SET arr $ '{"arr":["test", "one", "two","three"]}'
```

Then when you query `JSON.GET arr $.arr[*]` it seems to get more or less what you are looking for:

![image](https://github.com/RedisGrafana/grafana-redis-datasource/assets/42971704/ada7b7de-5adb-46bd-993a-dfb4e0499765)

**Comment by slorello89** [comment]
Think this is answered now? feel free to reopen if I'm missing something.
