### ISSUE TITLE
TS.MRANGE GROUPBY / REDUCE

### ISSUE THREAD

**Issue by jameswest368** [RedisGrafana/grafana-redis-datasource#286]
## Summary
I'd like to be able to use the GROUP BY function of TS.MRANGE but I don't see the option for it?

## Relevant information
Looks like the GROUP BY options was added in version 1.6 of the RedisTimeSeries plugin - how far behind are we in supporting that version?

https://redis.io/commands/ts.mrange/

**Comment by slorello89** [comment]
Hi @jameswest368 - It's on my todo list.
