### ISSUE TITLE
CLIENT INFO fails

### ISSUE THREAD

**Issue by bityob** [RedisGrafana/grafana-redis-datasource#298]
### Describe the bug
Can't use "client info" comand, getting `ERR unknown command 'CLIENT'` as response.

### Version
2.1.1

### Steps to reproduce
1. Choose CLI type
2. Execute `CLIENT INFO`

### Expected behavior
Should return current connection info

### Screenshots
![image](https://github.com/RedisGrafana/grafana-redis-datasource/assets/20026896/4c590b9f-bdbf-46c1-95c5-f4d7a42bfbc1)

**Comment by slorello89** [comment]
CLIENT INFO is a Redis 6.2 command - are you on Redis 6.2+?

**Comment by bityob** [comment]
@slorello89 

Yes

```
# Server
redis_version:6.2.6
```

**Comment by nail-sirazitdinov** [comment]
@bityob `ERR unknown command 'CLIENT'` is the response from the Redis server. Can you confirm it with `CLIENT INFO` using redis-cli or any other client, e.g. [RedisInsight](https://redis.com/redis-enterprise/redis-insight/)?
What Redis flavor are you running (OSS, Enterprise, any specific SaaS)?

**Comment by slorello89** [comment]
+1 to Nail's point - works on the redis/redis-stack-server running v6.2.12 for me.

**Comment by bityob** [comment]
@nail-sirazitdinov

I can confirm that it works now successfully on the redis we have (v6.2.6) with grafana too, doesn't know what happend last week.

I guess some confusion on our Grfana redis data sources settings. 

Thanks for helping, closing.
