### ISSUE TITLE
How to connect to Redislabs cluster?

### ISSUE THREAD

**Issue by mcao8888** [RedisGrafana/grafana-redis-datasource#63]
## Summary
How do we connect to Redislabs cluster?   If cluster FQDN is clusterA.production.int, default cluster port is 9443, and database port is customized to 15000 for example, what is the connection URL?

We're keep getting this error:  getInstance error: no pools available

This is not community Redis where the default port is 6379.

The screenshot in the doc is not correct for connecting to a real Redis cluster.

**Comment by mikhailredis** [comment]
Hello @mcao8888, thank you for your interest in the plug-in.

You should be able to connect to your database on port 15000 using Redis Data Source like `redis://clusterA.production.int:15000` or `clusterA.production.int:15000` and provide a password in Standalone mode. Do you use TLS/SSL or ACLs?

I will ask your Technical Account Manager to help you to connect.

This is how I connect to my Redis Enterprise database:
![Screen Shot 2020-09-28 at 3 35 08 PM](https://user-images.githubusercontent.com/47795110/94492939-45a88800-01a0-11eb-9220-2b26eabf50c6.png)

**Comment by mcao8888** [comment]
I was able to connect as you suggested (standalone, specific to a database, with the URL pointing to the node that the endpoint of the database resides on).

So we can only register 1 database at a time using standalone mode and not the entire cluster using the Redis Cluster mode?

Thanks

**Comment by mikhailredis** [comment]
@mcao8888 `Redis Cluster` is for OSS Redis Cluster (https://redis.io/topics/cluster-spec) not Redis Enterprise.

Unfortunately, the auto-populating of Redis databases using Redis Enterprise REST API is not supported in Redis Data Source.

Could you please provide more details on what you are looking for to achieve with Redis Data Source?

**Comment by mcao8888** [comment]
Similar to Redis Insight where you register cluster port (9443), master node url (clusterA.production.int), and Admin/password (for cluster, not a specific database).   This then would register all the databases on the cluster without having to register 1 database at a time.  When you have numerous databases in a multitenant scenario, this would help.

**Comment by mikhailredis** [comment]
@mcao8888 I agree, auto-populate similar to Redis Insight will be very useful.
I will check internally and get back to you.

**Comment by mikhailredis** [comment]
I have updated the tooltip for Client Type to avoid confusion between Redis OSS and Enterprise clusters. Also, it will be mentioned in the documentation. Auto-populate using Redis Enterprise API will be implemented as a part of the Redis Enterprise data source in the future versions.

**Comment by tanvp112** [comment]
> @mcao8888 `Redis Cluster` is for OSS Redis Cluster (https://redis.io/topics/cluster-spec) not Redis Enterprise.
> 
> Unfortunately, the auto-populating of Redis databases using Redis Enterprise REST API is not supported in Redis Data Source.
> 
> Could you please provide more details on what you are looking for to achieve with Redis Data Source?

I get the `getInstance error` when I am tried to connect to OSS Redis Cluster using the service endpoint (including the headless service). I can connect using `Standalone` but I suspect doing so will cause OPS report only one of the master node metric.

The tooltips is not much help, what is the URL to set in order to connect to a OSS Redis cluster?
