### ISSUE TITLE
All Redis Datasource timeout when one is not reachable

### ISSUE THREAD

**Issue by pab1it0** [RedisGrafana/grafana-redis-datasource#73]
### Describe the bug

All Datasource timeout when one is not reachable

### Version

1.2.0

### Steps to reproduce

1. Create more than one redis datasource, one that isn't reachable
2. Create dashboard for each datasource.
3. Goto the reachable datasource's dashboard and refresh -> Dashboard is updated with metrics
4. Goto the unreachable datasource's dashboard and refresh -> Dashboard freezes.
5. Go back to reachable datasource's dashboard and refresh -> Dashboard freezes.

### Expected behavior

Dashboard with reachable datasource should fetch metrics indifferently of other datasource's state.

**Comment by pab1it0** [comment]
@mikhailredis FYI.

**Comment by mikhailredis** [comment]
@pab1it0 Thank you for submitting the issue. I will check and get back to you.

**Comment by mikhailredis** [comment]
@pab1it0 I am sorry for the delay. I found the issue with the timeout, which is fixed in the upcoming release. This helps with this issue, but still, Redis Data Source is blocking when trying to open new connections.

I will investigate further.

**Comment by mikhailredis** [comment]
Opened the issue for Grafana SDK: https://github.com/grafana/grafana-plugin-sdk-go/issues/248

**Comment by mikhailredis** [comment]
PR submitted: https://github.com/grafana/grafana-plugin-sdk-go/pull/251
