### ISSUE TITLE
Multi-value variables with redis datasource

### ISSUE THREAD

**Issue by MathieuEtchepare** [RedisGrafana/grafana-redis-datasource#74]
## Summary
Hi, I started using this datasource recently and I had a special use case that I don't know is feasible or not.
I have a first grafana variable that is a multi-value select. Its source is a Redis instance.
If I select more than one value the result is stored in the variable as {1,2,3} (if I selected 1,2 and 3 in first select)
My goal is to use these values to get multiple keys in another grafana redis variable.

Is there something I didn't understand or is it impossible?

Thank you in advance

**Comment by MathieuEtchepare** [comment]
Thanks for your answer.
I just noticed that the last part of my question was really unclear and I'm sorry for that.

As a matter of fact, I'm using a first variable to display geographical zones, let's say America, Europe and Asia.
For each I have a list in redis named after it with countries.
To sum up in redis I have:

- Regions [America, Europe, Asia]
- America [USA, Mexico, ...]
- Asia [China, Japan, ...]
- Europe [France, UK, Spain, ...]

If I select in the first variable America and Europe, is there a way to display the union of these two zones in a second variable?
(By the way, the dashboard, you linked is awesome, I'm going to use it a lot thank you)

**Comment by mikhailredis** [comment]
Hello @MathieuEtchepare,

  There are multiple advanced variable format options for variables in Grafana which you can play with: https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/

  Do you keep countries as LIST data type or SET?

**Comment by MathieuEtchepare** [comment]
I'm keeping them as a set

**Comment by mikhailredis** [comment]
@MathieuEtchepare, one of the possible solutions is to use EVAL command: 
```
eval "return redis.call('sunion',${region:singlequote})" 0
```
![Screen Shot 2020-10-14 at 12 26 11 PM](https://user-images.githubusercontent.com/47795110/96036747-c2329c00-0e19-11eb-84a2-d388d6932952.png)

I am checking with the team for other options.

**Comment by nail-sirazitdinov** [comment]
Hi @MathieuEtchepare 
The trick with LUA script should work fine on a single shard deployment.

Another option is to utilize [RedisGears](https://oss.redislabs.com/redisgears/intro.html) module. RedisGears is a powerful framework for the execution of the functions. It supports Python and C API.

Here is an example of the script
```
gb = GB('CommandReader')
gb.flatmap(lambda x:  execute('SUNION',*x[1].split(",")))
gb.register(trigger='SUNION')
```

Which you can load to the database with RedisGears enabled like:
`redis-cli -p 6379 RG.PYEXECUTE "$(cat sunion.py)"`

To execute the trigger:
`redis-cli -p 6379 RG.TRIGGER SUNION 'America,Europe'`

Use `RG.TRIGGER SUNION $<your-multi-select-variable>` to display in Grafana.

Thank you
__
Nail

**Comment by mikhailredis** [comment]
Hello @MathieuEtchepare, please let us know if LUA or RedisGears solution works for you.

**Comment by MathieuEtchepare** [comment]
Hi,

Sorry for the late response, I was on other subjects these days...
I am going to use the LUA solution as I only need a simple line of code for now, but I will think about RedisGears if I need a more complex solution.

Thanks for your time, I really appreciate the effort you put into helping me.

Have a nice day! 😃

**Comment by mikhailredis** [comment]
@MathieuEtchepare, thank you for the update.
 
Please let us know if you need anything else.
