### ISSUE TITLE
Graph data from HGETALL

### ISSUE THREAD

**Issue by lexicalunit** [RedisGrafana/grafana-redis-datasource#76]
## Summary

I have a hash of days to counts stored in redis using HSET. I'm getting that data out with HGETALL. I can see it as a table, but there appears to be no way to actually graph it.

![Screen Shot 2020-10-14 at 3 22 57 PM](https://user-images.githubusercontent.com/1903876/96051879-4b090200-0e31-11eb-9ba0-5ec14c207012.png)

And when I try to switch the visualization to graph I just get:

![Screen Shot 2020-10-14 at 3 24 17 PM](https://user-images.githubusercontent.com/1903876/96051922-5d833b80-0e31-11eb-8d1a-1506f14ae8fb.png)

## Relevant information

There doesn't seem to be any way to switch my x-axis to use the `Day` values and my y-axis to the counts.

The data as stored in redis is simply a hash like:

```
{
    "2020-07-23": 8,
    "2020-07-26": 1,
    "2020-07-27": 1,
    "2020-07-28": 33,
    "2020-07-29": 1,
    "2020-07-30": 54,
    "2020-07-31": 40,
    "2020-08-01": 42,
    "2020-08-02": 53,
    "2020-08-04": 1,
    "2020-08-10": 2,
    "2020-08-13": 2,
    "2020-08-14": 3,
    "2020-08-18": 3,
    "2020-08-19": 2,
    "2020-08-20": 2,
    "2020-08-21": 4,
    "2020-08-22": 78,
    "2020-08-23": 19,
    "2020-08-24": 43,
    "2020-08-25": 5,
    "2020-08-26": 2,
    "2020-08-27": 4,
    "2020-08-28": 1,
    "2020-08-31": 3,
    "2020-09-02": 1,
    "2020-09-04": 1,
    "2020-09-09": 1,
    "2020-09-10": 14,
}
```

**Comment by mikhailredis** [comment]
Hello @lexicalunit, thank you for submitting the issue.

  My initial analysis is that HSET returns each column as a string or number and Grafana expects time to be a `time.Time` type. I have to take a closer look.
  Is it an existing project or you are developing it? Hash is not the best data type to store time-series data. I would recommend taking a look at [RedisTimeSeries](https://oss.redislabs.com/redistimeseries/) which is fully supported in the plug-in.

  Please let me know if RedisTimeSeries works. I will investigate and get back to you.

**Comment by lexicalunit** [comment]
It's something I'm developing. I'm just trying to figure out how to do something like "counts by day" which seems to be really freaking difficult or else I'm just using the wrong tools. I'm using RedisCloud for my redis hosting and I'm not sure I have access to the time series module, at least not without paying (I'm on the free plan right now). At least, the TS commands don't seem to work on my cli when I connect to the db.

**Comment by mikhailredis** [comment]
@lexicalunit Redis Cloud has a RedisTimeSeries module available in AWS/Mumbai region. All modules are a part of Pro subscriptions in all regions.

  You can add your data to RedisTimeSeries and then aggregate values per day: https://oss.redislabs.com/redistimeseries/commands/#tsrangetsrevrange
  You can try using Docker: `docker run -p 6379:6379 -it --rm redislabs/redistimeseries`.

  I am still checking regarding the graph.

**Comment by lexicalunit** [comment]
@mikhailredis I don't see that option here: https://elements.heroku.com/addons/rediscloud#details

**Comment by mikhailredis** [comment]
@lexicalunit, I was talking about Redis Cloud Essential, which you can try to free https://redislabs.com/try-free/ and it's available in Oregon (us-west-2) region.

Please let me know if you have any questions.

**Comment by lexicalunit** [comment]
Ah, I was trying to stay within the ecosystem of heroku. Ty for the info tho!

**Comment by mikhailredis** [comment]
@lexicalunit RedisTimeSeries is available in Heroku if you want to give it a try.
Are you still developing your application using Hashes? In the upcoming version, the hash will be represented as fields instead of rows, to be able to stream it.

We can implement a special option to display hash as time-series if you are still interested.

**Comment by lexicalunit** [comment]
I switched over to using a read-only account via a postgresql data source for a lot of the graphs I wanted to create. I'm still using redis for some metrics that I want to display though.

For the redis panels I just have to manually get many multiple values individually as their own series and then display them as a bar graph. For example:

![Screen Shot 2020-12-20 at 5 40 47 PM](https://user-images.githubusercontent.com/1903876/102730849-e8c5f500-42ea-11eb-8acf-af5d97079fe7.png)

For the postgresql panels I'm able to just have one single series in grafana that uses a `GROUPY BY` to identify the individual lines dynamically based on the data itself. It's not clear to me that something like this would even be possible with redis:

![Screen Shot 2020-12-20 at 5 41 38 PM](https://user-images.githubusercontent.com/1903876/102731016-815c7500-42eb-11eb-9e13-ad7314ce4c46.png)

**Comment by mikhailredis** [comment]
@lexicalunit You can use Hash to store metrics and display them as bar graphs in the upcoming version using HGETALL or HMGET commands.

Regarding the Postgres query, as I said before it can be done using RedisTimeSeries, which is now available in Heroku.
You can add time-series samples for data using TS.ADD command with labels and then display using TS.MRANGE command.

Please let me know if you have any questions.

**Comment by mikhailredis** [comment]
Here is the blog how I did something similar: https://redislabs.com/blog/how-to-use-the-new-redis-data-source-for-grafana-plug-in/

**Comment by lexicalunit** [comment]
Thanks for the blog post, I'll dig into this!

**Comment by mikhailredis** [comment]
I am going ahead and close this issue. Let me know if you need anything else.
