### ISSUE TITLE
SLOWLOG GET only returns 10 rows

### ISSUE THREAD

**Issue by sabir-piludiya** [RedisGrafana/grafana-redis-datasource#78]
In Plugin, SLOWLOG GET returns only 10 Rows with timestamp, duration and command. I need the data of more than 10. Eg. 128 Slowlog.
I also tried **SLOWLOG GET 128** in custom command option, However in that case it's not showing like the field wise.

Is it not supported or If anyone can help.

**Comment by mikhailredis** [comment]
@sabir-piludiya Thank you for submitting the issue. The SLOWLOG GET (https://redis.io/commands/slowlog) command by default return 10 entries. To display more than 10 we can improve Query Editor and add additional parameter.

I will let you know when ready.

**Comment by mikhailredis** [comment]
@sabir-piludiya, Additional `Size` parameter was added for Slowlog and merged to master. It will be available in the upcoming release. Meanwhile, you can build the data source yourself following BUILD instructions.

Please let me know if you have any questions.
