### ISSUE TITLE
getInstance error: ERR command is not allowed

### ISSUE THREAD

**Issue by aengusrooneygrafana** [RedisGrafana/grafana-redis-datasource#81]
## Summary
When adding Redis Cluster datasource to Grafana, we are getting the following error message: 
`getInstance error: ERR command is not allowed` 

## Relevant information
Error: 
![image](https://user-images.githubusercontent.com/54800912/96574002-2ef0df00-12cf-11eb-8751-7e660cf4de01.png)

Connection string from:
![image](https://user-images.githubusercontent.com/54800912/96574242-7aa38880-12cf-11eb-8f39-bbc4f6f31b2e.png)

redis://redis-14224.rediscluster.qa.xxxxxxxx.com:14224 

following error:
getInstance error: ERR command is not allowed

Also trying a connection string (note the difference of '/9' at end of URL):  
redis://redis-14224.rediscluster.qa.xxxxxxxx.com:14224/9  

produces the following message: 
`getInstance error: no pools available` 

Can you please help or advise on configuration of Redis Cluster datasource?  

Thanks, 
A.

**Comment by mikhailredis** [comment]
Hello @aengusrooneygrafana, thank you for opening the issue.

`Redis Cluster` means "OSS Cluster API" which may not be enabled for this Redis database. Please check if it's enabled using Redis Enterprise Cluster manager UI. If it's not enabled, use `Standalone` mode.

Regarding /9 at the end of the URL, it means that Redis Data Source should connect to logical database 9, which are not supported in Redis Enterprise.

Let me know if the data source was able to connect to Redis database or have any questions.

**Comment by aengusrooneygrafana** [comment]
Thank you Mikhail, that works.  

Can we update the README with this information please?  

https://github.com/RedisGrafana/grafana-redis-datasource/#does-this-data-source-support-redis-cluster-and-sentinel 

Thanks, 
A.

**Comment by mikhailredis** [comment]
@aengusrooneygrafana, thank you for the update.
We are working on the documentation for Redis Data Source and we will describe each client type.
Thank you for the feedback and let us know if you need anything else.

**Comment by aengusrooneygrafana** [comment]
Thank you Mikhail - that's everything -thank you for your help!
