### ISSUE TITLE
Redis Timeseries only 30 seconds of data displayed  on Raspberry Pi

### ISSUE THREAD

**Issue by DGorringe** [RedisGrafana/grafana-redis-datasource#84]
## Summary
Hi guys
Firstly thanks for your hard work on building this software. I am a newbie to both grafana and redis. So please forgive my ignorance. I have tried to read manuals and follow guidance notes as much as possible.
I have a Redis instance receiving interrupt drive updates from a heading sensor, so only updates when sensor changes heading. I am using the Timeseries module with TS.MADD to input data into Redis which looks like it is working as designed.

I have built a grafana dashboard with a panel to output heading. Everything appears to work as expected for about 30 seconds then the output repeats the value that was read at the 30 second point in time. Looking at the output from the grafana data source query  it  build s three ts.range queries that cover the 30 second time period, then no longer changes the unix time in the ts.range query which sort corresponds to why I see the same data repeating.

When dashboard refreshed get another 30seconds of activity.

Is there a parameter I can change to make the panel span a wider time window without repeating the same value?

![image](https://user-images.githubusercontent.com/32269865/97118818-2ac82580-1704-11eb-90af-b1666850168c.png)

## Relevant information

Raspberry Pi4
Linux bopeep 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux
pi@bopeep:~$ grafana-server -v
Version 7.2.2 (commit: ad9d408ac2, branch: HEAD)
with plugins 
Reids Datasource v1.2.1
Redis-app v1.01

pi@bopeep:~$ redis-server -v
25417:C 25 Oct 2020 19:26:39.594 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
25417:C 25 Oct 2020 19:26:39.595 # Redis version=6.0.8, bits=32, commit=00000000, modified=0, pid=25417, just started

with modules RedisTimeseries and RedisGears installed
Client 
Ubuntiu 20.4 (64bit) Firefox 82.1(64bit)

log extrat to show repeating "ts.range" "master:bopeep:hull:imu:euler_headinguires which don ot increament the unixtime from to parameters -

1603655052.511886 [0 127.0.0.1:39574] "ts.range" "master:bopeep:hull:imu:euler_heading" "1603654738875" "1603655038876"
1603655052.518000 [0 127.0.0.1:39574] "ts.range" "master:bopeep:hull:tpa:base_air_pressure" "1603654738876" "1603655038877"
1603655052.521343 [0 127.0.0.1:39574] "ts.range" "master:bopeep:hull:imu:euler_heading" "1603654738877" "1603655038877"
1603655052.540356 [0 127.0.0.1:39574] "info" "stats"
1603655052.940467 [0 127.0.0.1:39574] "ts.range" "master:bopeep:hull:imu:euler_heading" "1603654738875" "1603655038876"
1603655052.963840 [0 127.0.0.1:39574] "ts.range" "master:bopeep:hull:tpa:base_air_pressure" "1603654738876" "1603655038877"
1603655052.997358 [0 127.0.0.1:39574] "ts.range" "master:bopeep:hull:imu:euler_heading" "1603654738877" "1603655038877"
1603655054.600913 [0 127.0.0.1:39578] "SELECT" "0"
1603655054.601426 [0 127.0.0.1:39578] "info" "stats"
1603655054.602670 [0 127.0.0.1:39578] "ts.range" "master:bopeep:hull:imu:euler_heading" "1603654738875" "1603655038876"
1603655054.606709 [0 127.0.0.1:39578] "ts.range" "master:bopeep:hull:tpa:base_air_pressure" "1603654738876" "1603655038877"
1603655054.610233 [0 127.0.0.1:39578] "ts.range" "master:bopeep:hull:imu:euler_heading" "1603654738877" "1603655038877"
1603655054.617163 [0 127.0.0.1:39578] "info" "stats"
1603655054.935549 [0 127.0.0.1:39578] "ts.range" "master:bopeep:hull:imu:euler_heading" "1603654738875" "1603655038876"
1603655054.991245 [0 127.0.0.1:39578] "ts.range" "master:bopeep:hull:tpa:base_air_pressure" "1603654738876" "1603655038877"
1603655054.998787 [0 127.0.0.1:39578] "ts.range" "master:bopeep:hull:imu:euler_heading" "1603654738877" "1603655038877"

**Comment by mikhailredis** [comment]
Hello @DGorringe, thank you for submitting the issue and trying RedisTimeSeries with Redis Data Source.

The start and stop values for `TS.RANGE` you see in the MONITOR command, Redis Data Source takes from Grafana's top panel. In your case, it's the last 5 minutes. So if you set your dashboard to refresh every 10 seconds - 1-minute interval, you should see different values.

I am not sure I understand the issue with repeating values. If you do the `TS.RANGE` command using `redis-cli` or in the table do you see different values or not?

**Comment by DGorringe** [comment]
Hi Mikail

Thanks for you prompt response. Your words have helped me analyse what I 
was seeing and how I should change my usage of grafana to get the 
required result.

I was expecting the  generated TS.RANGE query to look something like 
"TS.RANGE measurement <from_unixtime>  +" so would get the values from 
the starting point with the dataset returned constantly extending.  What 
I was seeing was multiple "TS.RANGE measurement <from_unixtime> 
<to_unixtime>". with different time ranges show in "redis-cli monitor" 
which lead me to believe new queries were being generated by grafana. I 
had assumed this was how grafana was moving the end time range. The 
multiple redundant TS.RANGE queries stopped when I logged out of grafana 
then logged in again.

But the way it actually works is to generate a single query "TS.RANGE 
measurement <from_unixtime> <to_unixtime>" with the interval specified 
by the time range parameters, So the returned data set only returns with 
in the time range, What was confusing me was the time range covered 
about 30 seconds of live data so I was seeing new readings being added 
to data set  before time window  closed and no new readings where added.

The light bulb came on when thinking about this, so changed query to 
just use TS.GET so the latest reading would returned with each refresh.

  I should know by now not to make assumptions. It has helped me 
understand how the grafana query, time range  and streaming  work.

Thanks you

David

**Comment by mikhailredis** [comment]
@DGorringe Great, thank you for the update.

As I understand you were able to see more than 30 seconds on data, correct? Can I help you with anything else?
