### ISSUE TITLE
Graph data from HMGET by using streaming

### ISSUE THREAD

**Issue by Kaharu** [RedisGrafana/grafana-redis-datasource#85]
### Summary
I have a hash data like this and update value each 10 seconds.
> 
    test1        10
    test2        20
    test3        30
    test4        40

I want to get that data out with HMGET and monitor by streaming like this.
![image](https://user-images.githubusercontent.com/73450318/97125691-0b6ae000-1778-11eb-8a57-82c8fce25831.png)

### Relevant information
Grafana: v7.2.1 windows
ReidsDatasource: v1.2.0

When I try to switch the visualization to graph I can't get.
And when I set streaming at visual of table,  I get only last data of hash.
![image](https://user-images.githubusercontent.com/73450318/97125603-ca72cb80-1777-11eb-89d5-4c39d9e6e409.png)

**Comment by mikhailredis** [comment]
@Kaharu Thank you for submitting the issue. We have to add support for the `HMGET` command and streaming should be working when output will be parsed as separate columns.

I will work on it and get back to you shortly.

**Comment by Kaharu** [comment]
When will Version 1.3 which support HMGET command be released?

**Comment by mikhailredis** [comment]
@Kaharu, I am sorry for the delay. I will work on it and get back to you this week.

**Comment by Kaharu** [comment]
It is difficult to support this function?
Sorry I don't mean to rush you, but I only want to know when will be released.

**Comment by mikhailredis** [comment]
@Kaharu Pull request was merged to master and will be available in the upcoming release 1.3.

**Comment by mikhailredis** [comment]
@Kaharu You can build a data source yourself follow BUILD instructions if you want to try the HMGET command before the release. I am planing to finish release 1.3 this week and submit it to Grafana for review over the weekend.

**Comment by Kaharu** [comment]
Very Thank you!
I  apologize for my frequent contacts and appreciate your cooperation.

**Comment by mikhailredis** [comment]
@Kaharu You are very welcome. Please let me know if there is anything else.

**Comment by mikhailredis** [comment]
@Kaharu I am sorry for another delay. Grafana plugin team is on vacation and I will submit a new version as soon as they are back. Thank you.
