### ISSUE TITLE
How to retain matrices.

### ISSUE THREAD

**Issue by siddharthshubhampal** [RedisGrafana/grafana-redis-datasource#86]
I am using this plugin to fetch data from Redis Cloud endpoints in grafana. I have entered multiple Redis datasources with datasource as variable and realtime graphs are getting plotted. But if I change datasource or refresh "streaming dashboard", Old matrices vanishes. How can I retain streaming dashboard data to get historical data in grafana.

**Comment by mikhailredis** [comment]
Hello @siddharthshubhampal, thank you for opening the issue and using Redis Data Source.

Streaming dashboard data is stored in the browser's memory and cleared out after refresh.

You can see historical data on your Cloud account dashboard (https://app.redislabs.com). I will ask your Technical Account Manager to get in touch with you to discuss the best monitoring solution for your needs.
