### ISSUE TITLE
Allow to run queries from [Explore] tab in grafana

### ISSUE THREAD

**Issue by shay-berman** [RedisGrafana/grafana-redis-datasource#87]
Cannot run query from `Expore` tab in grafana.
1. Example of get command (cannot edit the key at all):
![image](https://user-images.githubusercontent.com/1079649/97451783-c348ea80-193c-11eb-9361-e41f2a5f9711.png)

2. Also cannot run clusterINFO command
![image](https://user-images.githubusercontent.com/1079649/97451899-df4c8c00-193c-11eb-8d9f-9ac530513253.png)

### Describe the solution you'd like
To be able to run queries from Expore tab the same as inside grafana dashboard widgets.

### Additional context
It works well in dashboard widgets but not with the expore mode.

Thanks

**Comment by mikhailredis** [comment]
@shay-berman Please check that Redis datasource configured correctly, I was able to use Explore using the latest release and configured Redis Data Source.

Regarding `key` looks like it intersects with one of the reserved variables. I will look into it and may need to rename it.

**Comment by mikhailredis** [comment]
@shay-berman Thank you for opening the issue. The `Key` was updated to `KeyName` to avoid conflict with reserved option in the Grafana Explore.
