### ISSUE TITLE
Ploting LRANGE

### ISSUE THREAD

**Issue by 1nv1** [RedisGrafana/grafana-redis-datasource#88]
### Summary
I’m working using redis’ lists, in my case I get the value with the query (CLI) “LRANGE key idx idx”. I can’t chart it but I can see in a table. It's possible support LRANGE for ploting? Best regards.

![imagen](https://user-images.githubusercontent.com/2840417/98030683-28df2000-1df0-11eb-8d59-8b58f7be7aac.png)

![imagen](https://user-images.githubusercontent.com/2840417/98030628-12d15f80-1df0-11eb-8722-4887a8a637b9.png)

**Comment by mikhailredis** [comment]
@1nv1 Thank you for submitting the issue. I will take a look and get back to you shortly.

**Comment by mikhailredis** [comment]
@1nv1 I am sorry for the delay. I updated CLI to check if returned strings are numbers and updated the type to be able to plot. It will be a part of the upcoming release.

Please take a look and let me know if it's what you are looking for.
![Screen Shot 2020-12-21 at 9 02 37 PM](https://user-images.githubusercontent.com/47795110/102851144-e5f10000-43cf-11eb-813b-ce468c598285.png)

**Comment by 1nv1** [comment]
Hi @mikhailredis. Yes, that's. Amazing! Thanks a lot.
