### ISSUE TITLE
Store streaming data from Redis Enterprise Cloud

### ISSUE THREAD

**Issue by leewei05** [RedisGrafana/grafana-redis-datasource#90]
## Summary

We are using Redis Enterprise Cloud on GCP. Since this is a managed service, we can only use the default Enterprise Cloud console for monitoring. The data on Enterprise Console is not granular enough and it cannot send different alerts to us. This plugin's Redis Streaming dashboard might be a solution for us. However, it seems like this plugin can only display live data, is it? Once I refresh my Grafana browser, it re-collects the display data. Is there any methods that we can store these streaming data locally for history searching? As far as I know, we cannot use Prometheus directly with Redis Enterprise Cloud.

## Relevant information

This plugin is awesome though, very handy to use for testing Redis database. 😄

**Comment by mikhailredis** [comment]
Hello @leewei05, thank you for your question and I am sorry for the delayed response.

  Streaming in the Redis Data Source was designed to display live data and does not allow to store them locally. You can use 3rd party collector tools to store those metrics in Prometheus or other databases.

  I will ask your Technical Account Manager to discuss various Monitoring solutions with you.

**Comment by leewei05** [comment]
@mikhailredis, thanks for the reply! I've already ask them for some Monitoring solutions.
In the mean time, we'll try to use other data collector tools.
