### ISSUE TITLE
redis_datasource_darwin_amd64 cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by iamshreeram** [RedisGrafana/grafana-redis-datasource#91]
### Problem
Ran into issue while opening grafana (standalone) with redis-datasource plugin installed. Pop-up was prompted saying - "redis_datasource_darwin_amd64 cannot be opened because the developer cannot be verified"

### Solution
System Preferences > Security & Privacy -> set to allow redis-datasource_darwin_amd64

### Error Message
<img width="407" alt="Screen Shot 2020-11-25 at 12 46 30 AM" src="https://user-images.githubusercontent.com/7752805/100193162-e2458880-2eb8-11eb-8205-1bb0257999cc.png">

### Note
This should be common issue for people installing Redis-datasource. We need to address this issue in any of documentation. Any thoughts?

**Comment by mikhailredis** [comment]
@iamshreeram Thank you for submitting the issue. What version of Mac OS do you use?

  I tried Grafana standalone with Redis-datasource on my Catalina and don't remember any issues. Nothing was reported so far. Have you tried to start it manually or you saw this warning message when started Grafana?

  How did you install and start Grafana? using brew?

  Please send me more details to reproduce the issue.

**Comment by iamshreeram** [comment]
@mikhailredis 
Installation
1. Redis Grafana : Downloaded the redis plugin (.zip) and unzipped it in `/data/plugins` directory
2. Grafana : Stand-alone. Just download the grafana zip file; Unzip it and execute the binary `./grafana-server`. No installation.

I think you wouldn't see this issue because, the plugin might already be verified in your system preference.

**Comment by mikhailredis** [comment]
@iamshreeram Thank you for the detailed instructions. I will add it to the documentation.
