### ISSUE TITLE
Get "NOAUTH Authentication required" error with sentinel

### ISSUE THREAD

**Issue by luvs** [RedisGrafana/grafana-redis-datasource#92]
I have redis/sentinel cluster. Redis and sentinel have 'requirepass' param in config (password equal).

When I configure datasource for sentinel I get error "NOAUTH Authentication required", but if I set standalone plugin works.

![111](https://user-images.githubusercontent.com/731500/100241870-3b5afe00-2f45-11eb-9515-16fe2ed0050f.jpg)

**Comment by mikhailredis** [comment]
Hello @luvs, thank you for submitting the issue. I have not tried using a password with Sentinel.
I will take a look and get back to you shortly.

**Comment by mikhailredis** [comment]
@luvs I am sorry for the delay. The fix merged to master and will be available in the upcoming release.
You are welcome to build a plug-in yourself following BUILD instructions before the release.
Please let me know if you have any questions.
