### ISSUE TITLE
Unable to connect to redis-datasource

### ISSUE THREAD

**Issue by iamshreeram** [RedisGrafana/grafana-redis-datasource#93]
## Summary
I'm seeing error while connecting to redis-data source running on docker. `/api/datasources/1/health` is failing with HTTP 503 after 2.5 minutes. This may need some timeout set. 

## Snapshot
<img width="1659" alt="grafana_redis_timeout" src="https://user-images.githubusercontent.com/7752805/100371271-24f88500-2fcd-11eb-97ba-ef8fa276a00e.png">

**Comment by mikhailredis** [comment]
Hello @iamshreeram, the Redis Data Source use Radix Golang client and has connect timeout preconfigured. I will take a look why it takes longer to timeout after 2.5 minutes.

  Are you running Docker on Windows, Mac or Linux? You may not be able to connect to outside network with your Docker configuration. Could you try in network `host` mode?

**Comment by iamshreeram** [comment]
@mikhailredis , 
1. Yes. I was running the redis on docker (on mac).
2. The host mode was working good. 

Today I was able to connect to docker as well. I don't know what fixed the issue. 

But, Can we make this timeout a configurable value. As you can see in the snapshot, the Waiting (TTFB) was close to 2.5 mins). If we can document this, it might help people.

**Comment by mikhailredis** [comment]
@iamshreeram This timeout is configurable in the Advanced settings. I tried to reproduce the issue using the latest version from the `master` branch and the session successfully timeout after the configured value.

I will experiment more trying to reproduce the issue.

**Comment by mikhailredis** [comment]
@iamshreeram Thank you for reporting the issue. I found the problem and merged the fix to master.
Please let me know if there is anything else.
