### ISSUE TITLE
Cannot specify more than 6 addresses in cluster configuration

### ISSUE THREAD

**Issue by alexey-danilov** [RedisGrafana/grafana-redis-datasource#94]
### Describe the bug
Cannot specify more than 6 addresses in cluster configuration

### Version
1.2.1

### Steps to reproduce
In one of our setups we are using version 1.2.0 of redis plugin and can successfully add more that 6 redis node addresses into a datasource. However, in 1.2.1 version whenever more that 6 addresses a provided, there is an error (see the screenshot). All of the addresses are actually working, i.e. if provided in different combinations and less than 6 in total.

Version of grafana is same in both instances: v7.1.1 (3039f9c3bd)

### Expected behavior
It should be possible to provide more than 6 addresses for redis cluster

**Comment by alexey-danilov** [comment]
![Screen Shot 2020-12-09 at 11 41 20 AM](https://user-images.githubusercontent.com/4075759/101613222-2cc81880-3a14-11eb-9f56-a73753fe35d0.png)

**Comment by alexey-danilov** [comment]
UPDATE: based on this diff, I think version 1.2.1 is not compatible with grafana < 7.2.0: https://github.com/RedisGrafana/grafana-redis-datasource/commit/dd4140b0a47081d6e388be67702e14a838a461fc#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by alexey-danilov** [comment]
UPDATE 2: rolling back to version 1.2.0 did not help either, still the same error

**Comment by mikhailredis** [comment]
@alexey-danilov Thank you for opening the issue. It's not clear what do you mean by `backing DB for grafana`.
Were you able the solve the issue or not?
