### ISSUE TITLE
Support fetching from RedisJSON datasource

### ISSUE THREAD

**Issue by xkilian** [RedisGrafana/grafana-redis-datasource#95]
### Is your enhancement related to a problem? Please describe.
Ability to display data stored in RedisJSON in Grafana. Most notably for the table plugin.

### Describe the solution you'd like
Ability to connect to a ReidsJSON datastore, query, search, filter and display data Grafana.

### Describe alternatives you've considered
JSON API Grafana datasource which connects to http JSON PATH compliant APIs.

**Comment by mikhailredis** [comment]
@xkilian Thank you for the feature request. Do you have any particular command from the [RedisJSON](https://oss.redislabs.com/redisjson/commands/) module you want to use?

We started to introduce support for Redis modules and I will target to add support for some RedisJSON command in 1.3.1.

**Comment by xkilian** [comment]
The principal use-case would be GETting data from RedisJSON et being able to display it Grafana. Perhaps MGET as well. Second order would be meta-data about what is being displayed (TYPE).
I think KEYS would also be important but more from a searching perspective which should be built-in to the datasource. But could also be a method of list the keys explicitely.  I am not sure I see much value in writing to RedisJSON for most users at this ime from Grafana.
So: KEYS, GET, MGET, TYPE.

**Comment by mikhailredis** [comment]
@xkilian Thank you, I will let you know when ready.

**Comment by xkilian** [comment]
I still look forward to this feature and will provide testing. Thank you for this great plugin.

**Comment by mikhailredis** [comment]
@xkilian I am sorry for the delay. I am working on it.

**Comment by trungswat** [comment]
Hi, 
Still looking forward to hearing something new about supporting rejson.
Thank you

**Comment by mikhailredis** [comment]
@trungswat I am sorry for the delay, I am working on it right now.
